apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-cert
  namespace: hermes
spec:
  commonName: 'opensearchhermesadmin.{{ .Values.global.region }}'
  duration: 8760h
  renewBefore: 720h
  issuerRef:
    name: opensearch-hermes-ca-issuer
    kind: Issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - client auth
    - server auth
  secretName: admin-cert
