{{- $values := .Values }}
{{- if $values.alerts.enabled }}
{{- range $path, $bytes := .Files.Glob "alerts/*.alerts.tpl" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ printf "opensearch-%s" $path | replace "/" "-" | trimSuffix ".tpl" }}
  labels:
    app: opensearch
    tier: os
    type: alerting-rules
    prometheus: {{ required ".Values.alerts.prometheus missing" $values.alerts.prometheus | quote }}

spec:
{{- with $ }}
{{ tpl (printf "%s" $bytes) . | indent 2 }}
{{- end }}

{{- end }}
{{- end }}
