apiVersion: v1
kind: Service
metadata:
  name: metal-maintenance-operator
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: sanitized
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    app.kubernetes.io/instance: metal-maintenance-operator
  type: ClusterIP
