apiVersion: v2
name: chorus
description: A Helm chart for Chorus - tool for object storage data migration
type: application
version: 0.4.0
appVersion: "v0.7.10"
sources:
  - https://github.com/clyso/chorus
maintainers:
  - name: senolcolak
  - name: sumitarora2786
dependencies:
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 1.0.0
  - name: chorus
    repository: oci://harbor.clyso.com/chorus
    version: 0.4.0
