apiVersion: v2
name: chorus
description: A Helm chart for Chorus - tool for object storage data migration
type: application
version: 0.3.0
appVersion: "v0.7.8"
dependencies:
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: ">= 0.0.0"
  - name: chorus
    repository: oci://harbor.clyso.com/chorus
    version: 0.3.0
