apiVersion: v2
name: dual-deployment-operator
description: Per-shoot deployment of the dual-deployment-operator controller for SAP CC
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: dual-deployment-operator
    alias: controller
    condition: controller.enabled
    repository: oci://keppel.global.cloud.sap/i-cant-believe-its-not-cloud-infrastructure-dev/helm-dual-deployment-operator
    version: 0.1.0
