# templates/configmap-cp-seed.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "archer.fullname" . }}-cp-seed
  labels:
    {{- include "archer.labels" . | nindent 4 }}
data:
  manage-services.sh: |
    {{ include (print .Template.BasePath "/bin/_manage-services.sh.tpl") . | nindent 4 }}
