{{- $region := .Values.global.region | required "missing value for .Values.global.region" }}
{{- $rmq := .Values.linuxbridge_agent.rabbitmq | required "missing value for .Values.linuxbridge_agent.rabbitmq" }}
{{- $user := required ".Values.linuxbridge_agent.rabbitmq.defaultUser required" $rmq.defaultUser }}
{{- $rmqNamespace := $rmq.namespace | default "monsoon3" }}
{{- $clusterDomain := .Values.global.clusterDNSSearchDomain | default "cluster.local" }}
{{- $host := $rmq.host | default (printf "neutron-rabbitmq.%s.svc.%s" $rmqNamespace $clusterDomain) }}
{{- if and (not $rmq.host) ($rmq.use_discovery_record | default false) }}
  {{- $tld := .Values.global.tld | required "missing value for .Values.global.tld when .Values.linuxbridge_agent.rabbitmq.host is not set" }}
  {{- $host = printf "neutron-rabbitmq.cc.%s.%s" $region $tld }}
{{- end }}
{{- $data := dict
    "host" $host
    "port" ($rmq.port | default 5672)
    "virtual_host" ($rmq.virtual_host | default "")
    "user" (printf "vault+kvv2:///secrets/%s/neutron/rabbitmq-user/%s/username" $region $user)
    "password" (printf "vault+kvv2:///secrets/%s/neutron/rabbitmq-user/%s/password" $region $user)
}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "archer.neutronSecretName" . }}
type: Opaque
stringData:
  OS_DEFAULT__TRANSPORT_URL: {{ include "utils.rabbitmq_url" (tuple . $data) | trim | quote }}
