{{- $region := .Values.global.region | required "missing value for .Values.global.region" }}
{{- $tld    := .Values.global.tld    | required "missing value for .Values.global.tld" }}
{{- $rmq    := .Values.linuxbridge_agent.rabbitmq | required "missing value for .Values.linuxbridge_agent.rabbitmq" }}
{{- $user   := required ".rabbitmq.defaultUser required" $rmq.defaultUser }}
{{- $host   := $rmq.host | default (printf "neutron-rabbitmq.%s.%s" $region $tld) }}
{{- $data := dict
    "host"         $host
    "port"         ($rmq.port | default 5672)
    "virtual_host" ($rmq.virtual_host | default "")
    "user"     (printf "vault+kvv2:///secrets/%s/neutron/rabbitmq-user/%s/username" $region $user)
    "password" (printf "vault+kvv2:///secrets/%s/neutron/rabbitmq-user/%s/password" $region $user)
}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.linuxbridge_agent.secretName }}
type: Opaque
stringData:
  OS_DEFAULT__TRANSPORT_URL: {{ include "utils.rabbitmq_url" (tuple . $data) | trim | quote }}
