{
 "title": "Kubernetes APIServer",
 "description": "Metrics for Kubernetes API Server",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "API Server Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Server RPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[5m]))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Current Inflight Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests) by (requestKind)",
     "legendFormat": "{{requestKind}}"
    }
   ]
  },
  {
   "title": "Latency - p99 (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_latencies_bucket{verb!~\"WATCH|CONNECT\"}[5m])) by (le) ) / 1e+06"
    }
   ]
  },
  {
   "title": "API Server Response Duration (Seconds)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum{verb!~\"WATCH|CONNECT\"}[5m])) ",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "API Server Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{code=~\"^(?:4..)$|^(?:5..)$\"}[5m])) by (code)>0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "API Server Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "API Server Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{code!~\"^(?:4..)$|^(?:5..)$\"}[5m])) by (code)>0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "API Server Requests (by Verb)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[5m])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "API Requests (by Resource)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[5m])) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "API Requests by client (non-kube-*)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{client!~\"kubelet.*|kube-scheduler.*|kube-controller.*|kube-apiserver.*|kube-proxy.*\"}[5m])) by (client) > 0",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "API Requests by client (kube-*)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{client=~\"kubelet.*|kube-scheduler.*|kube-controller.*|kube-apiserver.*|kube-proxy.*\"}[5m])) by (client)>0",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "API Server Requests by server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(rate(apiserver_request_count[5m])) by (instance)>0",
     "legendFormat": "{{instance}} ",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_latencies_bucket{verb!~\"WATCH|CONNECT\"}[5m])) by (le, resource) ) / 1e+06",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}