{
 "title": "Calico: Felix",
 "description": "Dashboard for monitoring Project Calico's per-host agent, Felix.  Project Calico provides CNI networking and security for Kubernetes.  Felix is responsible for calculating and applying the per-node dataplane state.  It also collects flow logs and other metrics.",
 "tags": [
  "kubernetes",
  "calico",
  "felix",
  "bpf",
  "dataplane"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "top_n", "label": "Top N limit", "query": "10,1,5,20,50,100,1000,10000" },
   { "name": "instance_label", "label": "Instance label", "query": "{{instance}}" }
  ]
 },
 "panels": [
  { "title": "Cluster-wide metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes in datamodel",
   "type": "timeseries",
   "description": "Total number of Node resources that Felix \"sees\" in the datamodel.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    { "expr": "max(felix_cluster_num_hosts)", "legendFormat": "Nodes" }
   ]
  },
  {
   "title": "Number of policies/profiles/tiers",
   "type": "timeseries",
   "description": "Total number of network Policies and Profiles (an internal policy-like resource used to represent namespaces/service accounts).",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "max(felix_cluster_num_policies)",
     "legendFormat": "Policies"
    },
    {
     "expr": "max(felix_cluster_num_profiles)",
     "legendFormat": "Profiles"
    },
    { "expr": "max(felix_cluster_num_tiers)", "legendFormat": "Tiers" }
   ]
  },
  {
   "title": "Endpoints in datamodel",
   "type": "timeseries",
   "description": "Total number of Endpoints (Pods/VMs/host endpoints) in the datamodel as seen by Felix.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max(felix_cluster_num_workload_endpoints)",
     "legendFormat": "Workload"
    },
    {
     "expr": "max(felix_cluster_num_host_endpoints)",
     "legendFormat": "Host"
    }
   ]
  },
  { "title": "Process metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Felix restarts/hr (top $top_n)",
   "type": "timeseries",
   "description": "Number of times the Felix process restarted in 1 hour moving window.  Note that Felix restarts (within the calico-node pod) when its configuration is changed so some restarts are expected when adjusting the FelixConfiguration resource.  In addition, Felix is restarted when the pod is restarted or upgraded.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk($top_n, changes(process_start_time_seconds[1h])) > 0",
     "legendFormat": "$instance_label"
    }
   ]
  },
  {
   "title": "Felix datastore resyncs/hr (top $top_n)",
   "type": "timeseries",
   "description": "Number of times Felix resynced with the datastore (for example reconnecting with Typha).  Resyncs are normal if Typha is rebalancing load or restarting during upgrade etc.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "topk($top_n, changes(felix_resyncs_started[1h])) > 0",
     "legendFormat": "$instance_label"
    }
   ]
  },
  {
   "title": "CPU Usage (top $top_n)",
   "type": "timeseries",
   "description": "CPU usage of the Felix process only; does not include sub-processes such as iptables.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($top_n, rate(process_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "$instance_label"
    }
   ]
  },
  {
   "title": "Open file descriptors(top $top_n)",
   "type": "timeseries",
   "description": "Number of open file descriptors.  If this trends upwards over time, indicates a leak.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "targets": [
    { "expr": "topk($top_n, process_open_fds)", "legendFormat": "$instance_label" }
   ]
  },
  {
   "title": "Runtime GC rate/min (top $top_n)",
   "type": "timeseries",
   "description": "Number of garbage collections performed over time.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "topk($top_n, rate(go_gc_duration_seconds_count[$__rate_interval]))*60",
     "legendFormat": "$instance_label"
    }
   ]
  },
  {
   "title": "Runtime GC target heap size (top $top_n)",
   "type": "timeseries",
   "description": "The Go runtime's current target heap size.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, avg_over_time(go_memstats_next_gc_bytes[5m]))",
     "legendFormat": "$instance_label"
    }
   ]
  },
  {
   "title": "Runtime GC target heap size (average)",
   "type": "timeseries",
   "description": "The Go runtime's current target heap size.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "avg(go_memstats_next_gc_bytes)", "legendFormat": "$instance_label" }
   ]
  },
  {
   "title": "Process memory (RSS) (top $top_n)",
   "type": "timeseries",
   "description": "Felix process memory usage (resident set size).  does not include sub-processes/other components of calico-node.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, process_resident_memory_bytes)",
     "legendFormat": "$instance_label"
    }
   ]
  },
  {
   "title": "Active resources on each node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active local endpoints (top $top_n)",
     "type": "timeseries",
     "description": "Number of workload and host endpoints on each node.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk($top_n, felix_active_local_endpoints)",
       "legendFormat": "$instance_label"
      }
     ]
    },
    {
     "title": "Active local policies (top $top_n)",
     "type": "timeseries",
     "description": "Number of policies that are active on each node.  Policies are active when they apply to a local endpoint.  Only active policies consume dataplane resources.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk($top_n, felix_active_local_policies)",
       "legendFormat": "$instance_label"
      }
     ]
    },
    {
     "title": "Active local selectors (top $top_n)",
     "type": "timeseries",
     "description": "Number of label selectors that are active on each node.  Label selectors become active when used in a rule of an active policy.  Each label selector has an ongoing CPU cost proportional to the churn rate of endpoints.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk($top_n, felix_active_local_selectors)",
       "legendFormat": "$instance_label"
      }
     ]
    }
   ]
  },
  { "title": "Calculation graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Calculation graph load (top $top_n)",
   "type": "timeseries",
   "description": "Percentage of the time that the calculation graph thread is actively updating the desired state of the local node.  Approaching 100% indicates that the calculation graph is overloaded.\n\nOverload can be caused by lack of a CPU reservation on the calico-node pod, or by a too-small CPU reservation, or by very high datastore churn rate.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($top_n, rate(felix_calc_graph_update_time_seconds_sum[$__rate_interval]))",
     "legendFormat": "$instance_label"
    }
   ]
  },
  {
   "title": "Calculation graph updates/s (top $top_n)",
   "type": "timeseries",
   "description": "Rate of calculation graph updates",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "rate(felix_calc_graph_update_time_seconds_count[$__rate_interval])",
     "legendFormat": "$instance_label"
    }
   ]
  },
  {
   "title": "99%ile calculation update time (top $top_n)",
   "type": "timeseries",
   "description": "The 99%ile time to update the calculated desired state of the dataplane",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top_n, felix_calc_graph_update_time_seconds{quantile=\"0.99\"}) ",
     "legendFormat": "$instance_label"
    }
   ]
  },
  { "title": "Dataplane: common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Dataplane update load (top $top_n)",
   "type": "timeseries",
   "description": "Fraction of time that the dataplane thread is actively updating the dataplane.  Approaching 100% indicates the dataplane is overloaded.  Updates will be delayed and batched resulting in increased update latency.\n\nOverload can be caused by high churn; very large rule sets; lack of a CPU reservation on the calico-node pod, or by a too-small CPU reservation on calico-node.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($top_n, rate(felix_int_dataplane_apply_time_seconds_sum[$__rate_interval]))",
     "legendFormat": "$instance_label"
    }
   ]
  },
  {
   "title": "Dataplane operations/min (top $top_n)",
   "type": "timeseries",
   "description": "Rate of dataplane operations, including updates to the dataplane and periodic resyncs.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "topk($top_n, 60*rate(felix_int_dataplane_apply_time_seconds_count[1m]))",
     "legendFormat": "$instance_label"
    }
   ]
  },
  {
   "title": "99%ile dataplane update time (top $top_n)",
   "type": "timeseries",
   "description": "The 99%ile tiem to update the dataplane in felix's main dataplane update loop.  Longer times indicate increasing latency to update the dataplane with new updates from the datastore.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top_n, felix_int_dataplane_apply_time_seconds{quantile=\"0.99\"})",
     "legendFormat": "$instance_label"
    }
   ]
  },
  {
   "title": "Dataplane subprocess errors (top $top_n)",
   "type": "timeseries",
   "description": "Rate of errors returned from subprocesses such as iptables/ipset/etc.  Some background errors are expected due to resource contention in the kernel but high error rates should be investigated.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk($top_n, rate(felix_ipset_errors[$__rate_interval]) + rate(felix_iptables_restore_errors[$__rate_interval]) + rate(felix_iptables_save_errors[$__rate_interval]))",
     "legendFormat": "$instance_label"
    }
   ]
  },
  { "title": "Dataplane: iptables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Iptables rules (top $top_n)",
   "type": "timeseries",
   "description": "Number of Calico-owned iptables rules",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "topk($top_n, sum by(instance) (felix_iptables_rules))",
     "legendFormat": "$instance_label"
    }
   ]
  },
  {
   "title": "IP sets (top $top_n)",
   "type": "timeseries",
   "description": "Number of Calico-owned IP sets",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "targets": [
    {
     "expr": "topk($top_n, felix_ipsets_calico)",
     "legendFormat": "$instance_label"
    }
   ]
  },
  { "title": "Dataplane: eBPF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Events/s (top $top_n)",
   "type": "timeseries",
   "description": "Rate of events sent from BPF programs to Felix.  Events are used to tell Felix about new flows.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "topk($top_n, rate(felix_bpf_events{type!=\"lost\",type!=\"no_sink\"}[$__rate_interval])) ",
     "legendFormat": "$instance_label type={{type}}"
    }
   ]
  },
  {
   "title": "Lost events (top $top_n)",
   "type": "timeseries",
   "description": "Number of kernel-to-Felix events lost due to buffer overruns (Felix not keeping up with the event stream).",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
   "targets": [
    {
     "expr": "topk($top_n, increase(felix_bpf_events{type=\"lost\"}[$__rate_interval])) ",
     "legendFormat": "$instance_label type={{type}}"
    }
   ]
  },
  {
   "title": "Conntrack table entries (top $top_n)",
   "type": "timeseries",
   "description": "Number of conntrack table entries seen at the last conntrack table garbage collection.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "topk($top_n, felix_bpf_conntrack_used)",
     "legendFormat": "$instance_label"
    }
   ]
  },
  {
   "title": "Conntrack sweep duration (top $top_n)",
   "type": "timeseries",
   "description": "Time taken to scan the eBPF conntrack table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "topk($top_n, felix_bpf_conntrack_sweep_duration)",
     "legendFormat": "$instance_label"
    }
   ]
  },
  {
   "title": "Flow logs dataplane: iptables/nftables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFLOG events/s (top $top_n)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "topk($top_n, rate(felix_nflog_logs_received[$__rate_interval]))",
       "legendFormat": "$instance_label"
      }
     ]
    },
    {
     "title": "NFLOG buffer overruns (top $top_n)",
     "type": "timeseries",
     "description": "Number of times the kernel-to-Felix buffer overran resulting in lost events (and hence missing flow log information)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 57 },
     "targets": [
      {
       "expr": "topk($top_n, increase(felix_nflog_buffer_overruns[$__rate_interval]))",
       "legendFormat": "$instance_label"
      }
     ]
    },
    {
     "title": "NFLOG backlog size (top $top_n)",
     "type": "timeseries",
     "description": "Number of buffered connection information objects waiting to be sent from the NFLOG reader to the log collector.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "topk($top_n, clamp_min(felix_nflog_aggregates_created-felix_nflog_aggregates_flushed, 0))",
       "legendFormat": "$instance_label"
      }
     ]
    },
    {
     "title": "NFLOG flush wait time (top $top_n)",
     "type": "timeseries",
     "description": "Fraction of the time that the NFLOG reader thread spends waiting to send logs downstream.  Time spent waiting cannot be spent reading logs.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk($top_n, rate(felix_nflog_block_time_seconds[$__rate_interval]))",
       "legendFormat": "$instance_label group={{groupNum}}"
      }
     ]
    }
   ]
  },
  { "title": "Flow logs collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Flow logs collector conntrack load (top $top_n)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($top_n, rate(felix_collector_conntrack_processing_latency_seconds_sum[$__rate_interval]))",
     "legendFormat": "$instance_label group={{groupNum}}"
    }
   ]
  },
  {
   "title": "Cached flows (top $top_n)",
   "type": "timeseries",
   "description": "Number of pre-aggregation flows that the collector is tracking information about.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk($top_n, felix_collector_epstats)",
     "legendFormat": "$instance_label"
    }
   ]
  }
 ]
}