{
 "title": "CoreDNS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(coredns_dns_request_count_total[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum (rate(coredns_forward_request_count_total[5m]))",
     "legendFormat": "forwarded"
    }
   ]
  },
  {
   "title": "Requests per instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(coredns_dns_request_count_total[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request latency (99th percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "forwarded"
    }
   ]
  },
  {
   "title": "Requests by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (rate(coredns_dns_request_type_count_total[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Respones by rcode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (rcode) (rate(coredns_dns_response_rcode_count_total[5m]))",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Forwarded respones by rcode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (rcode) (rate(coredns_forward_response_rcode_count_total[5m]))",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Success Cache Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(coredns_cache_size{type=\"success\"})"
    }
   ]
  },
  {
   "title": "Denial Cache Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(coredns_cache_size{type=\"denial\"})"
    }
   ]
  },
  {
   "title": "Cache hits/misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (rate(coredns_cache_hits_total[5m]))",
     "legendFormat": "{{type}} hits"
    },
    {
     "expr": "sum (rate(coredns_cache_misses_total[5m]))",
     "legendFormat": "{{type}} misses"
    },
    {
     "expr": "sum(rate(coredns_cache_hits_total[5m]))/(sum(rate(coredns_cache_hits_total[5m]))+sum(rate(coredns_cache_misses_total[5m])))",
     "legendFormat": "hit ratio"
    }
   ]
  }
 ]
}