{
 "title": "Kubernetes DNS",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "calculatedInterval": "2s",
     "error": "No metric specified",
     "expr": "sum(rate(skydns_skydns_dns_request_count_total[5m])) by (system)",
     "legendFormat": "{{system}}",
     "period": "300",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22deriv(skydns_dns_request_count%5B2m%5D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-7-30%2021%3A2%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "calculatedInterval": "2s",
     "error": "No metric specified",
     "expr": "sum(rate(skydns_skydns_dns_cachemiss_count_total[5m]))",
     "legendFormat": "Cache Miss",
     "period": "300",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22deriv(skydns_dns_request_external_count%5B2m%5D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-7-30%2021%3A1%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "calculatedInterval": "2s",
     "expr": "histogram_quantile(0.9, sum(rate(skydns_skydns_dns_request_duration_seconds_bucket[5m])) by (le,system))",
     "legendFormat": "{{system}}",
     "period": "300",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22skydns_dns_error_count%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-7-30%2021%3A6%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "calculatedInterval": "2s",
     "expr": "sum(rate(skydns_skydns_dns_error_count_total[5m])) by (system)",
     "legendFormat": "{{system}}",
     "period": "300",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22skydns_dns_error_count%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-7-30%2021%3A6%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  }
 ]
}