{
 "title": "Kubernetes Container Resources",
 "description": "see https://blog.freshtracks.io/a-deep-dive-into-kubernetes-metrics-part-3-container-resource-metrics-361c5ee46e66",
 "tags": [
  "prometheus",
  "kubernetes"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_memory_working_set_bytes, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{namespace=\"$namespace\"}, pod_name)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{namespace=\"$namespace\", pod_name=~\"$pod\"}, container_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory satur.",
   "type": "singlestat",
   "description": "maximum ratio of allocated resident memory : memory limit\n\nThis shows the max. observed exhaustion of the container's memory limit, showing the container that is most close to the limit. Note: 100%  saturation means OOMKill!",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(container_memory_saturation_ratio{namespace=\"$namespace\",container_name=~\"$container\", pod_name=~\"$pod\"} >= 0)"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "singlestat",
   "description": "average ratio of throttled CPU time : totally requested CPU time\n\nThis shows  how much a process is slowed down by its CPU limit. In a cluster designed for peak loads, the values should be near 0% at all times. In an economic setup, the value should still be low, raising only when peak loads occur.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_cpu_saturation_ratio{namespace=\"$namespace\",container_name=~\"$container\",pod_name=~\"$pod\"} >= 0)"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "singlestat",
   "description": "Actual aggregated CPU usage : requested CPU usage\n\nThis graph shows how much of the total requested CPU cores would be used if there was no limit.\n\nThis number should be below 100% for responsiveness but not too far away from it for economic reasons.\n\nFormula: (container_cpu_cfs_throttled_seconds_total + container_cpu_usage_seconds_total)  / \n kube_pod_container_resource_requests{resource=\"cpu\"}",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(container_cpu_utilization_ratio{namespace=\"$namespace\",container_name=~\"$container\", pod_name=~\"$pod\"} >= 0)"
    }
   ]
  },
  {
   "title": "Memory util.",
   "type": "singlestat",
   "description": "Actual RAM usage : requested RAM usage",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(container_memory_utilization_ratio{namespace=\"$namespace\",container_name=~\"$container\", pod_name=~\"$pod\"} >= 0)"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "description": "Total resident memory used by containers",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",name!=\"POD\",container_name!=\"POD\",container_name=~\"$container\",pod_name=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Req. Memory",
   "type": "singlestat",
   "description": "Total memory requested",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\",container=~\"$container\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "description": "Total CPU cores used by containers",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}[5m])) + sum(irate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}[5m])) )"
    }
   ]
  },
  {
   "title": "Req. CPU",
   "type": "singlestat",
   "description": "Total CPU cores requested in manifests",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$namespace\",container=~\"$container\", pod=~\"$pod\"})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "resident memory used by container\n\nformula: container_memory_working_set_bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",name!=\"POD\",container_name!=\"POD\",container_name=~\"$container\",pod_name=~\"$pod\"}) by (namespace, pod_name, container_name)",
     "legendFormat": "{{pod_name}}/{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Saturation / Limit Exhaustion",
   "type": "graph",
   "description": "ratio used memory : max. allowed memory according to limit\n\nformula: container_memory_working_set_bytes / kube_pod_container_resource_limits_memory_bytes",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_memory_saturation_ratio{namespace=\"$namespace\",container_name=~\"$container\", pod_name=~\"$pod\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Actual vs. Requested Memory Utilization",
   "type": "graph",
   "description": "ratio currently used memory : requested memory\n\nThis graph shows how the actual memory allocation of a container matches the declared resource requirements. A value above 100% indicates overbooking, i.e.the container may be scheduled to a node with insufficient available memory.\n\nformula: container_memory_working_set_bytes / kube_pod_container_resource_requests{resource=\"memory\"}",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_memory_utilization_ratio{namespace=\"$namespace\",container_name=~\"$container\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}/{{container_name}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "1. Used CPU seconds\n2. CPU seconds lost due to CFS applying limits\n(1. container_cpu_usage_seconds 2. container_cpu_cfs_throttled_seconds)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container_name=~\"$container\", pod_name=~\"$pod\"}[5m]) ",
     "legendFormat": " {{pod_name}}/ {{container_name}}"
    },
    {
     "expr": "irate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\",container_name=~\"$container\", pod_name=~\"$pod\"}[5m]) > 0",
     "legendFormat": "throttled {{pod_name}}/{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU Saturation / Throttling Ratio",
   "type": "graph",
   "description": "ratio throttled CPU seconds : used CPU seconds\n\nformula: container_cpu_cfs_throttled_seconds / (container_cpu_usage_seconds + container_cpu_cfs_throttled_seconds)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_cpu_saturation_ratio{namespace=\"$namespace\",container_name=~\"$container\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}/{{container_name}}"
    }
   ]
  },
  {
   "title": "Actual vs. Requested CPU Utilization, Throttled secs.",
   "type": "graph",
   "description": "ratio actual CPU usage : requested CPU usage\n\nThis graph shows how the CPU requirements of the process match the declared resource requirement. A value above 100% shows that the process would consume much more CPU time than requested if no limit was set. \n \nformula: (container_cpu_cfs_seconds_total + container_cpu_cfs_throttled_seconds_total) / kube_pod_container_resource_requests{resource=\"cpu\"}",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio{namespace=\"$namespace\",container_name=~\"$container\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}/{{container_name}}"
    },
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\",container_name=~\"$container\", pod_name=~\"$pod\"}[5m])) by (namespace, pod_name, container_name)",
     "legendFormat": "throttled {{pod_name}}/{{container_name}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU secs.",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container_name=~\"$container\", pod_name=~\"$pod\"}[5m])) by (namespace, pod_name, container_name)",
     "legendFormat": "consumed CPU secs. {{pod_name}}/{{container_name}}"
    },
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\",container_name=~\"$container\", pod_name=~\"$pod\"}[5m])) by (namespace, pod_name, container_name)",
     "legendFormat": "throttled CPU secs.  {{pod_name}}/{{container_name}}"
    }
   ]
  },
  {
   "title": "CPU periods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_cfs_periods_total{namespace=\"$namespace\",container_name=~\"$container\", pod_name=~\"$pod\"}[5m])) by (namespace, pod_name, container_name)",
     "legendFormat": "requested CPU periods  {{pod_name}}/{{container_name}}"
    },
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\",container_name=~\"$container\", pod_name=~\"$pod\"}[5m])) by (namespace, pod_name, container_name)",
     "legendFormat": "throttled CPU periods  {{pod_name}}/{{container_name}}"
    }
   ]
  }
 ]
}