{
 "title": "VPA Recommendations",
 "description": "Vertical Pod Autoscalar Recommendations vs. Utilization vs. Requests & Limits",
 "tags": [
  "Autoscaling",
  "VPA"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "recommendation",
    "label": "Recommendation",
    "query": "target,uncappedtarget,lowerbound,upperbound"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_verticalpodautoscaler_labels, namespace)"
   },
   {
    "name": "targetName",
    "label": "Target",
    "query": "label_values(kube_verticalpodautoscaler_labels{namespace=\"$namespace\"}, target_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory $recommendation vs Memory Usage",
   "type": "graph",
   "description": "Shows the recommendations that the VPA gives as target usage. The graph also shows the actual usage of each container.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$targetName(.+)\", container!=\"\", container!=\"POD\"}) by (container,pod)",
     "legendFormat": "actual usage: {{pod}}/{{container}} "
    },
    {
     "expr": "kube_verticalpodautoscaler_status_recommendation_containerrecommendations_$recommendation{resource=\"memory\", namespace=\"$namespace\", target_name=\"$targetName\"}",
     "legendFormat": "recommendation: {{container}}"
    }
   ]
  },
  {
   "title": "VPA Memory Recommendations vs Requests and Limits",
   "type": "graph",
   "description": "Shows the recommendation of the VPA and compares it to the requests and limits of all containers in a pod. \n\n**Requests and/or limits may not reflect useful values if they are not defined for each container in a pod.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "kube_verticalpodautoscaler_status_recommendation_containerrecommendations_$recommendation{namespace=\"$namespace\", target_name=\"$targetName\", resource=\"memory\"}",
     "legendFormat": "recommendation: {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", pod=~\"$targetName(.+)\"}) by (container,pod)",
     "legendFormat": "requests: {{pod}}-{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", pod=~\"$targetName(.+)\"}) by (container,pod)",
     "legendFormat": "limits: {{pod}}-{{container}} "
    }
   ]
  },
  {
   "title": "CPU $recommendation vs CPU Usage",
   "type": "graph",
   "description": "Shows the recommendations that the VPA gives as target usage. The graph also shows the actual usage of each container.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$targetName-(.+)\", container!=\"\", container!=\"POD\"}[$__rate_interval])) by (container,pod) * 1000",
     "legendFormat": "actual usage: {{pod}}/{{container}}"
    },
    {
     "expr": "sum(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_$recommendation{resource=\"cpu\", namespace=\"$namespace\", target_name=\"$targetName\"}) by (container) * 1000",
     "legendFormat": " recommendation: {{container}}"
    }
   ]
  },
  {
   "title": "VPA CPU Recommendations vs Requests and Limits",
   "type": "graph",
   "description": "Shows the recommendation of the VPA and compares it to the requests and limits of all containers in a pod. \n\n**Requests and/or limits may not reflect useful values if they are not defined for each container in a pod.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_verticalpodautoscaler_status_recommendation_containerrecommendations_$recommendation{namespace=\"$namespace\", target_name=\"$targetName\", resource=\"cpu\"}) by (container) * 1000\r",
     "legendFormat": "recommendation: {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", pod=~\"$targetName(.+)\"}) by (container,pod) * 1000",
     "legendFormat": " requests: {{pod}}/{{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\", pod=~\"$targetName(.+)\"}) by (container,pod) * 1000",
     "legendFormat": "limits: {{pod}}/{{container}}"
    }
   ]
  }
 ]
}