{{- if .Values.global.db_region | hasPrefix "qa" }}

kind: Deployment
apiVersion: apps/v1

metadata:
  name: limitas-data-metrics

spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    # When scraping Prometheus metrics from this pod, we intentionally do not
    # add any labels to distinguish different pod names, so that there is no
    # break in the metrics on pod restart. Because of this, we can only run at
    # most one pod in this deployment at all times. Otherwise scraping would
    # fail because all pods would try to submit metrics with identical labels.
    type: Recreate
  selector:
    matchLabels:
      name: limitas-data-metrics
  template:
    metadata:
      labels:
        name: limitas-data-metrics
      annotations:
        checksum/configmap: {{ include "limes/templates/configmap.yaml" . | sha256sum }}
        checksum/secret: {{ include "limes/templates/secret.yaml" . | sha256sum }}
        kubectl.kubernetes.io/default-container: metrics
    spec:
      volumes:
        - name: config
          configMap:
            name: limes
      containers:
        - name: metrics
          image: {{ include "limes_image" . }}
          imagePullPolicy: IfNotPresent
          args:
            - serve-data-metrics-v2
            - /etc/limes/limes.json
          env:
            {{ include "limes_common_envvars" . | indent 12 }}
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            timeoutSeconds: 10
            periodSeconds: 60
            initialDelaySeconds: 60
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /etc/limes
              name: config
          ports:
            - name: metrics
              containerPort: 8080
          {{- if .Values.limes.resources.enabled }}
          resources:
            limits:
                cpu: '1'
                memory: '500Mi'
            requests:
                cpu: '100m'
                memory: '500Mi'
          {{- end }}

{{- end }}
