{{- if .Values.limes.customer_seed -}}

apiVersion: "openstack.stable.sap.cc/v1"
kind: OpenstackSeed
metadata:
  name: limes-customer-seed

spec: {{ .Values.limes.customer_seed | toYaml | nindent 2 }}

{{- end -}}
