fullnameOverride: ipam-capi
webhook:
  enable: true
webhookInjector:
  repository: keppel.global.cloud.sap/ccloud-ghcr-io-mirror/SAP-cloud-infrastructure/webhook-injector
  tag: latest
controllerManager:
  manager:
    env:
      kubernetesServiceHost: apiserver-url
  serviceAccountName: ipam-capi-remote-webhook-injector
  podSecurityContext:
    runAsUser: 65532 # ensure sidecar and main controller run as same user, so they can share generated tls certs via emptyDir volume 
    runAsGroup: 65532
