apiVersion: v1
kind: Secret
metadata:
  name: chorus-secrets
type: Opaque
data:
  master-password: {{ printf "vault+kvv2:///compute-storage-api-secrets/%s/chorus/master-password/default/password" .Values.global.region | b64enc }}
  redis-password: {{ printf "vault+kvv2:///compute-storage-api-secrets/%s/chorus/redis-password/default/password" .Values.global.region | b64enc }}
