{{- if .Values.chorusSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: chorus-secrets
  labels:
    app.kubernetes.io/name: chorus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  master-password: {{ required "chorusSecrets.masterPassword is required" .Values.chorusSecrets.masterPassword | quote }}
  redis-password: {{ required "chorusSecrets.redisPassword is required" .Values.chorusSecrets.redisPassword | quote }}
{{- end }}
