apiVersion: v1
kind: Secret
metadata:
  name: chorus-secrets
type: Opaque
data:
  master-password: {{ required "chorus.dynamicCredentials vault path required" .Values.chorus.dynamicCredentials.masterPassword | b64enc | quote }}
  redis-password: {{ required "chorus.redis vault path required" .Values.chorus.redis.auth.password | b64enc | quote }}
