{{- range $regionName, $region := .Values.regions }}
{{- $shootName := default (printf "m-%s" $regionName) $region.shootName }}
{{- $clusterType := include "cc-shoots.clusterType" $ }}
---
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: {{ $shootName }}
  labels:
    cluster-type: {{ $clusterType }}
    greenhouse.sap/owned-by: containers
    greenhouse.sap/shoot-grafter-transport: {{ default "greenhouse-prod-sci" $.Values.greenhouseShootGrafter }}
    metadata.greenhouse.sap/region: {{ $regionName }}
spec:
  purpose: {{ default "production" $region.purpose }}
  cloudProfile:
    kind: CloudProfile
    name: openstack
  region: {{ $regionName }}
  networking:
    services: 10.55.0.0/16
  provider:
    type: openstack
  kubernetes:
    version: {{ $region.kubernetes.version }}

    kubeAPIServer:
      featureGates:
        AnonymousAuthConfigurableEndpoints: true
      structuredAuthentication:
        configMapName: {{ printf "%s-auth-%s" $clusterType $regionName }}
      {{- if $region.auditing.enabled }}
      auditConfig:
        auditPolicy:
          configMapRef:
            name: {{ default "audit-policy-cp" $region.auditing.auditPolicyConfigMapName }}
      {{- end }}
      encryptionConfig:
        resources:
        - configmaps
        - bmcsecrets
        provider:
          type: aescbc
  seedName: {{ default (printf "rt-%s" $regionName) $region.seedName }}
  {{- if $region.auditing.enabled }}
  extensions:
  - type: auditing
    providerConfig:
      apiVersion: auditing.extensions.gardener.cloud/v1alpha1
      kind: AuditConfiguration
      backends:
      - http:
          url: {{ $region.auditing.url }}
          tls:
            secretReferenceName: {{ default "auditing-mtls" $region.auditing.mtlsSecretName }}
  resources:
  - name: {{ default "auditing-mtls" $region.auditing.mtlsSecretName }}
    resourceRef:
      apiVersion: v1
      kind: Secret
      name: {{ default "auditing-mtls" $region.auditing.mtlsSecretName }}
  {{- end }}
{{- end }}
