{{- if .Values.extensions.auditing.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-policy-cp-garden
  namespace: garden
data:
  policy: |-
    {{- .Values.extensions.auditing.gardenPolicy | nindent 4 }}
{{- end }}
