{{- if .Values.extensions.auditing.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-policy-cp-virtual
  namespace: garden
data:
  policy: |-
    {{- .Values.extensions.auditing.virtualPolicy | nindent 4 }}
{{- end }}
