{{ if .Values.extensions.networkingProblemDetector.enabled -}}
{{- with .Values.extensions.networkingProblemDetector -}}
apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: shoot-networking-problemdetector
spec:
  resources:
  - kind: Extension
    type: shoot-networking-problemdetector
    {{- if .autoEnable }}
    autoEnable:
    {{- range .autoEnable }}
    - {{ . }}
    {{- end }}
    {{- end }}
  deployment:
    extension:
      values:
{{ include "cc-gardener.extension.mergeValues" (dict "values" .values "extensionContext" . "fallbackTag" .version) | indent 8 }}
      helm:
        ociRepository:
{{ include "cc-gardener.extension.ociRepository" (dict "ociRepository" .helm.ociRepository "fallbackTag" .version) | indent 10 }}
      policy: OnDemand
{{- end }}
{{- end }}
