{{ if .Values.extensions.calico.enabled -}}
{{- with .Values.extensions.calico -}}
apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: networking-calico
spec:
  resources:
  - kind: Network
    type: calico
  deployment:
{{- if .admission }}
    admission:
{{- if .admission.values }}
      values:
{{ include "cc-gardener.extension.mergeValues" (dict "values" .admission.values "fallbackTag" .version) | indent 8 }}
{{- end }}
{{- if and .admission.runtimeCluster .admission.runtimeCluster.helm .admission.runtimeCluster.helm.ociRepository }}
      runtimeCluster:
        helm:
          ociRepository:
{{ include "cc-gardener.extension.ociRepository" (dict "ociRepository" .admission.runtimeCluster.helm.ociRepository "fallbackTag" .version) | indent 12 }}
{{- end }}
{{- if and .admission.virtualCluster .admission.virtualCluster.helm .admission.virtualCluster.helm.ociRepository }}
      virtualCluster:
        helm:
          ociRepository:
{{ include "cc-gardener.extension.ociRepository" (dict "ociRepository" .admission.virtualCluster.helm.ociRepository "fallbackTag" .version) | indent 12 }}
{{- end }}
{{- end }}
    extension:
{{- if .runtimeClusterValues }}
      runtimeClusterValues:
{{ include "cc-gardener.extension.mergeValues" (dict "values" .runtimeClusterValues "parentValues" .values "fallbackTag" .version) | indent 8 }}
{{- end }}
{{- if .values }}
      values:
{{ include "cc-gardener.extension.mergeValues" (dict "values" .values "fallbackTag" .version) | indent 8 }}
{{- end }}
      helm:
        ociRepository:
{{ include "cc-gardener.extension.ociRepository" (dict "ociRepository" .helm.ociRepository "fallbackTag" .version) | indent 10 }}
      policy: OnDemand
{{- end }}
{{- end }}
