{{ if and .Values.extensions.auditing .Values.extensions.auditing.enabled -}}
{{- with .Values.extensions.auditing -}}
apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
  name: auditing
spec:
  resources:
  - kind: Extension
    type: auditing
    workerlessSupported: true
    lifecycle:
      reconcile: BeforeKubeAPIServer
      delete: AfterKubeAPIServer
      migrate: AfterKubeAPIServer
    clusterCompatibility:
    - garden
    - shoot
  deployment:
    admission:
{{- if and .admission .admission.values }}
      values:
{{ include "cc-gardener.extension.mergeValues" (dict "values" .admission.values "fallbackTag" .version) | indent 8 }}
{{- end }}
      runtimeCluster:
        helm:
          ociRepository:
{{ include "cc-gardener.extension.ociRepository" (dict "ociRepository" ((.admission).runtimeCluster).helm.ociRepository "fallbackTag" .version) | indent 12 }}
      virtualCluster:
        helm:
          ociRepository:
{{ include "cc-gardener.extension.ociRepository" (dict "ociRepository" ((.admission).virtualCluster).helm.ociRepository "fallbackTag" .version) | indent 12 }}
    extension:
{{- if .runtimeClusterValues }}
      runtimeClusterValues:
{{ include "cc-gardener.extension.mergeValues" (dict "values" .runtimeClusterValues "parentValues" .values "fallbackTag" .version) | indent 8 }}
{{- end }}
{{- if .values }}
      values:
{{ include "cc-gardener.extension.mergeValues" (dict "values" .values "fallbackTag" .version) | indent 8 }}
{{- end }}
      helm:
        ociRepository:
{{ include "cc-gardener.extension.ociRepository" (dict "ociRepository" .helm.ociRepository "fallbackTag" .version) | indent 10 }}
      policy: OnDemand
{{- end }}
{{ end -}}
