# The runtime values always need to be enabled to manage DNS records in designate + backups in swift.
{{ if .Values.extensions.openstack.enabled -}}
{{- with .Values.extensions.openstack -}}
apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: provider-openstack
spec:
  resources:
  - kind: BackupBucket
    type: openstack
  - kind: BackupEntry
    type: openstack
  - kind: Bastion
    type: openstack
  - kind: ControlPlane
    type: openstack
  - kind: DNSRecord
    type: openstack-designate
  - kind: Infrastructure
    type: openstack
  - kind: Worker
    type: openstack
  deployment:
{{- if .admission }}
    admission:
{{- if .admission.values }}
      values:
{{ include "cc-gardener.extension.mergeValues" (dict "values" .admission.values "extensionContext" . "fallbackTag" .version) | indent 8 }}
{{- end }}
{{- if and .admission.runtimeCluster .admission.runtimeCluster.helm .admission.runtimeCluster.helm.ociRepository }}
      runtimeCluster:
        helm:
          ociRepository:
{{ include "cc-gardener.extension.ociRepository" (dict "ociRepository" .admission.runtimeCluster.helm.ociRepository "fallbackTag" .version) | indent 12 }}
{{- end }}
{{- if and .admission.virtualCluster .admission.virtualCluster.helm .admission.virtualCluster.helm.ociRepository }}
      virtualCluster:
        helm:
          ociRepository:
{{ include "cc-gardener.extension.ociRepository" (dict "ociRepository" .admission.virtualCluster.helm.ociRepository "fallbackTag" .version) | indent 12 }}
{{- end }}
{{- end }}
    extension:
      runtimeClusterValues:
{{- if .runtimeClusterValues }}
{{ include "cc-gardener.extension.mergeValues" (dict "values" .runtimeClusterValues "parentValues" .values "extensionContext" . "fallbackTag" .version) | indent 8 }}
{{- end }}
        config:
          etcd:
            storage:
              provisioner: {{ $.Values.extensions.storage.provisioner | quote }}
              {{- if $.Values.extensions.storage.className }}
              className: {{ $.Values.extensions.storage.className | quote }}
              {{- end }}
              {{- if $.Values.extensions.storage.parameters }}
              parameters: {{ $.Values.extensions.storage.parameters | toYaml | nindent 16 }}
              {{- end }}
      values:
{{ include "cc-gardener.extension.mergeValues" (dict "values" .values "extensionContext" . "fallbackTag" .version) | indent 8 }}
        config:
          etcd:
            storage:
              provisioner: {{ $.Values.extensions.storage.provisioner | quote }}
              {{- if $.Values.extensions.storage.className }}
              className: {{ $.Values.extensions.storage.className | quote }}
              {{- end }}
              {{- if $.Values.extensions.storage.parameters }}
              parameters: {{ $.Values.extensions.storage.parameters | toYaml | nindent 16 }}
              {{- end }}
      helm:
        ociRepository:
{{ include "cc-gardener.extension.ociRepository" (dict "ociRepository" .helm.ociRepository "fallbackTag" .version) | indent 10 }}
      policy: OnDemand
{{- end }}
{{- end }}
