{{- if .Values.garden.virtualCluster.publicDomain }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.garden.name }}-apiserver-public
  namespace: garden
spec:
  dnsNames:
  - api.{{ .Values.garden.virtualCluster.publicDomain }}
  issuerRef:
    group: certmanager.cloud.sap
    kind: ClusterIssuer
    name: digicert-issuer
  secretName: {{ .Values.garden.name }}-apiserver-public-tls
  usages:
  - digital signature
{{- end }}

{{- if .Values.extensions.oidcAppsController.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shoot-dashboards-wildcard
  namespace: istio-ingress
spec:
  dnsNames:
  {{- for $dnsName := .Values.extensions.oidcAppsController.dashboardDnsNames }}
  - {{ $dnsName }}
  {{- end }}
  issuerRef:
    group: certmanager.cloud.sap
    kind: DigicertIssuer
    name: digicert-issuer
  secretName: {{ .Values.extensions.oidcAppsController.tlsSecretName required "missing value for .Values.extensions.oidcAppsController.tlsSecretName" }}
  usages:
  - digital signature
  - key encipherment
{{- end }}
