owner-info:
  support-group: containers
  service: tenso
  maintainers:
    - Stefan Majewsky
    - Stefan Voigt
    - Sandro Jäckel
    - Daniel Wagner
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/system/tenso-auto

# actual values come from separate file
