persephone:
  landscapes:
    - qa
    - canary
    - prod

owner-info:
  support-group: containers
  service: persephone
  maintainers:
    - Caio Ronchi
    - Fabian Ruff
    - Jan Knipper
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/system/persephone-metal
