apiVersion: v1
kind: ConfigMap
metadata:
  name: metal-onboarding-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: metal-onboarding-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
