{{- $values := .Values.alerts }}
{{- if $values.enabled }}
{{- range $path, $bytes := .Files.Glob "thanos-alerts/*.alerts.tpl" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ printf "cc3test-%s" $path | replace "/" "-" | trimSuffix ".tpl" }}
  labels:
    app: cc3test-tests
    thanos-ruler: {{ required "$values.thanos missing" $values.thanos }}
    absent-metrics-operator/disable: "true"

spec:
{{- with $ }}
{{ tpl (printf "%s" $bytes) . | indent 2 }}
{{- end }}

{{- end }}
{{- end }}
