ldapBindDnBasePrefix: "" # overwrite default value
ldapUserSearchBasePrefix: "OU=Employees"
ldapGroupSearchBasePrefix: "OU=Groups"

ldapUrl: url
ldapBaseOu: ou
ldapBindUser: user

# ldapAuthType: obfuscated_password
ldapBindPassword: pass
# ldapBindPassword: vault+kvv2:///path/to/secret

ldapAccessFilter: filter
sudoersGroups:
  - group

# sssd:
#   caseSensitive: false
