{{- $values := .Values }}
{{- if $values.alerts.enabled }}
{{- range $target, $cluster := $values.alerts.prometheus }}
{{- range $path, $bytes := $.Files.Glob (printf "alerts/%s/*.alerts" $target) }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "octavia-%s" $path | replace "/" "-" }}
  labels:
    app: octavia
    tier: os
    type: alerting-rules
    prometheus: {{ $cluster | quote }}
spec:
{{ printf "%s" $bytes | indent 2 }}

{{- end }}
{{- end }}
{{- end }}
