cluster:
  type: workerless
  seedType: management
  supportGroup: containers

kubernetes:
  version: 1.32.6
clusters:
  cluster1:
    region: ab-cd-1
    kubernetes:
      version: 1.32.6
auditing:
  enabled: false
  url: "https://auditing.test.svc.cluster.local"
