{{- $root := . }}
{{- $values := .Values.vrops }}
{{- if .Values.vrops.enabled }}
{{- range $target := .Values.global.targets }}
{{- if $values.alerts.enabled }}
{{- range $path, $bytes := $.Files.Glob "alerts/*.alerts.tpl" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ include "prometheusVMware.name" (list $target $root) }}{{ printf "-%s" $path | replace "/" "-" | trimSuffix ".tpl" }}
  labels:
    app: vrops-exporter
    prometheus: {{ include "prometheusVMware.name" (list $target $root) }}

spec:
{{- with $ }}
{{ tpl (printf "%s" $bytes) . | indent 2 }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
{{- end }}
