apiVersion: v1
kind: ConfigMap

metadata:
  name: tenso-auto

data:
  helm_deployment_cluster_regex: {{ .Values.tenso.helm_deployment_cluster_regex | required "missing value for .Values.tenso.helm_deployment_cluster_regex" | quote }}
  region_regex: {{ .Values.tenso.region_regex | required "missing value for .Values.tenso.region_regex" | quote }}
  awx_workflow_az_regex: {{ .Values.tenso.awx_workflow_az_regex | required "missing value for .Values.tenso.awx_workflow_az_regex" | quote }}
