apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-bin
  labels:
    system: openstack
    type: configuration
    component: nova
data:
{{ (.Files.Glob "bin/*").AsConfig | indent 2 }}
  db-migrate: |
{{ include (print .Template.BasePath "/bin/_db-migrate.tpl") . | indent 4 }}
  db-online-migrate: |
{{ include (print .Template.BasePath "/bin/_db-online-migrate.tpl") . | indent 4 }}
  nanny-db-archive-deleted-rows: |
{{ include (print .Template.BasePath "/bin/_nanny-db-archive-deleted-rows.tpl") . | indent 4 }}
  nanny-db-purge: |
{{ include (print .Template.BasePath "/bin/_nanny-db-purge.tpl") . | indent 4 }}
  nanny-db-soft-delete-excessive-instance-faults: |
{{ include (print .Template.BasePath "/bin/_nanny-db-soft-delete-excessive-instance-faults.tpl") . | indent 4 }}
