{{- $serviceDependencies := (include "nova.helpers.cell_services" (tuple . "api")) }}
{{- $conductorArgs := dict
  "name" "nova-conductor"
  "replicas" .Values.pod.replicas.conductor
  "config_file" .Values.conductor.config_file
  "dependencies" (dict "service" $serviceDependencies)
  "config_map_key" "nova-conductor.conf"
  "secret_keys" (list "api-rpc.conf" "cell0.conf")
}}
{{ include "nova.conductor_deployment" (tuple . $conductorArgs) }}
