# Delete db rows soft-deleted before more than older_than days from shadow
# tables.
{{- if .Values.nanny.db_purge.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nova-nanny-db-purge
  labels:
    system: openstack
    component: nova
    type: nanny
spec:
  schedule: {{ .Values.nanny.db_purge.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          {{- tuple . "nanny-db-purge" | include "job_metadata" | indent 10 }}
        spec:
          restartPolicy: OnFailure
          {{- include "utils.proxysql.job_pod_settings" . | indent 10 }}
          volumes:
          - name: container-init
            configMap:
              name: nova-bin
              defaultMode: 0755
          {{- include "utils.proxysql.volumes" . | indent 10 }}
          {{- include "utils.trust_bundle.volumes" . | indent 10 }}
          - name: nova-etc
            projected:
              sources:
              - configMap:
                  name: nova-etc
                  items:
                  - key:  nova.conf
                    path: nova.conf
                  - key:  nova-api.conf
                    path: nova-api.conf
                  - key:  logging.ini
                    path: logging.ini
                  - key:  release
                    path: release
              - secret:
                  name: nova-etc
                  items:
                  - key: api-db.conf
                    path: nova.conf.d/api-db.conf
                  - key: cell1.conf
                    path: nova.conf.d/cell1.conf
                  {{- if .Values.cell2.enabled }}
                  - key:  {{ .Values.cell2.name }}.conf
                    path: nova-{{ .Values.cell2.name }}.conf
                  {{- end }}
                  - key: keystoneauth-secrets.conf
                    path: nova.conf.d/keystoneauth-secrets.conf
                  {{- if .Values.audit.enabled }}
                  - key: audit-middleware.conf
                    path: nova.conf.d/audit-middleware.conf
                  {{- end }}
          initContainers:
          {{- tuple . (dict "service" (include "nova.helpers.database_services" .)) | include "utils.snippets.kubernetes_entrypoint_init_container" | indent 10 }}
          containers:
          - name: nanny
            image: {{ tuple . "api" | include "container_image_nova" }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              /container.init/nanny-db-purge
              exit_code=$?
              {{- include "utils.script.job_finished_hook" . | nindent 14 }}
              exit $exit_code
            env:
            - name: PYTHONWARNINGS
              value: {{ .Values.python_warnings | quote }}
            volumeMounts:
            - mountPath: /etc/nova
              name: nova-etc
            - mountPath: /container.init
              name: container-init
            {{- include "utils.proxysql.volume_mount" . | indent 12 }}
            {{- include "utils.trust_bundle.volume_mount" . | indent 12 }}
            resources:
              requests:
                memory: "5000Mi"
                cpu: "1000m"
              limits:
                memory: "5000Mi"
                cpu: "1000m"
          {{- include "utils.proxysql.container" . | indent 10 }}
{{- end }}