apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Host resources (Deployment, Services, Ingress, NetworkPolicy, ConfigMaps, Secrets, RBAC)
  - ../../host/overlays/rt-eu-de-1
  # Remote upstream ManagedResources (pre-rendered CRDs + RBAC + webhooks)
  - ../../remote/upstream/crds-and-rbac
  - ../../remote/upstream/webhooks
  # Remote custom resources (Namespace, custom RBAC for remote virtual cluster)
  - ../../remote/custom/overlays/rt-eu-de-1
