apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.hypervisorAgentsServiceAccountName | default .Release.Name }}
rules:
- apiGroups: ["kvm.cloud.sap"]
  resources: ["hypervisors"]
  verbs: ["get", "watch", "list"]
