# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0

apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: kmip-seed
  labels:
    {{- include "kmip.labels" . | nindent 4 }}
spec:
  requires:
  - monsoon3/keystone-seed
  - monsoon3/domain-default-seed

  services:
  - name: kmip-barbican
    type: key-management
    description: KMIP Key Management Service
    endpoints:
    - interface: public
      region: '{{ .Values.global.region }}'
      url: 'https://kmip.cc.{{ .Values.global.region }}.{{ .Values.global.tld }}'

  domains:
  - name: Default
    users:
    - name: kmip-barbican
      description: 'KMIP Barbican Service User'
      password: '{{ .Values.kmip.openstack_env.password | include "resolve_secret" }}'
      role_assignments:
      - project: service
        role: service
      - project: service
        role: keymanager_admin
