kind: Service
apiVersion: v1

metadata:
  name: kmip-barbican
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "kmip.restapiname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    system: openstack
    type: api
    component: kmip
  annotations:
    {{- include "utils.linkerd.pod_and_service_annotation" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "kmip.restapiname" . }}
  ports:
    - name: restapi
      port: 5005
      targetPort: 5005
      protocol: TCP
