{{- $region := $.Values.global.region | required "missing value for .Values.global.region" -}}
{{- $tld    := $.Values.global.tld    | required "missing value for .Values.global.tld"    -}}

kind: Ingress
apiVersion: networking.k8s.io/v1

metadata:
  name: s3-proxy
  namespace: content-repo
  annotations:
    kubernetes.io/tls-acme: "true"
    disco: "true"
    {{- if and $.Values.global.linkerd_enabled $.Values.global.linkerd_requested }}
    ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    {{- end }}

spec:
  tls:
    - secretName: tls-repo-new
      hosts:
        - 'repo-new.{{ $region }}.{{ $tld }}'
  rules:
    - host: 'repo-new.{{ $region }}.{{ $tld }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: s3-proxy
                port:
                  number: 80
