kind: Secret
apiVersion: v1

metadata:
  name: s3-proxy
  namespace: content-repo
  labels:
    system: openstack
    component: content-repo

data:
  access_key: {{ .Values.s3_proxy.bucket.access_key | required ".Values.s3_proxy.bucket.access_key is missing" | b64enc }}
  secret_key: {{ .Values.s3_proxy.bucket.secret_key | required ".Values.s3_proxy.bucket.secret_key is missing" | b64enc }}
