apiVersion: v2
name: kvm-ha-agent
description: A Helm chart for Kubernetes
type: application

version: 0.1.0

dependencies:
- name: kvm-ha-agent
  version: '0.1.4'
  repository: "oci://keppel.eu-de-1.cloud.sap/ccloud-helm"
- name: owner-info
  repository: "oci://keppel.eu-de-1.cloud.sap/ccloud-helm"
  version: '>= 0.0.0'
