owner-info:
  support-group: compute-storage-api
  service: masakari
  maintainers:
    - Felix Goldmann
    - Benjamin Helff
    - Paul Pickhardt
  helm-chart-url: https://github.com/cobaltcore-dev/kvm-ha-agent/chart/
