apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  {{- include "kube-state-metrics-remote.labels" . | nindent 4 }}
  name: kube-state-metrics-remote
  namespace: {{ .Values.remoteRBACNamespace}}
