{{- range $key, $cluster := .Values.clusters }}
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: {{ $key }}
  namespace: metal-{{ $key }}
  labels:
    cluster.x-k8s.io/cluster-name: {{ $key }}
spec:
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubernikusControlPlane
    name: {{ $key }}
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: Metal3Cluster
    name: {{ $key }}
{{- end }}
