apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metaldhcp
  labels:
    app.kubernetes.io/name: metaldhcp
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: ["dhcp.metal.ironcore.dev"]
    resources: ["oobsubnets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["dhcp.metal.ironcore.dev"]
    resources: ["dhcpleases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
