apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metaldhcp
  labels:
    app.kubernetes.io/name: metaldhcp
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metaldhcp
subjects:
  - kind: ServiceAccount
    name: metaldhcp
    namespace: {{ .Release.Namespace }}
