apiVersion: v1
kind: ServiceAccount
metadata:
  name: metaldhcp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: metaldhcp
    app.kubernetes.io/instance: {{ .Release.Name }}
