#!/bin/sh
until [ $(find /opt/harvest/shared -name '*.yaml' | wc -l) -gt 0 ]; do
    echo "Waiting for config file generated by netappsd-worker, sleeping 10 seconds..."
    sleep 10
done

# Find the config file in ./shared and start poller. The config file is rendered by the netappsd-worker container
exec find /opt/harvest/shared -name '*.yaml' -exec sh -c 'foo=$0; ln -s -f $foo /opt/harvest/harvest.yml && /opt/harvest/bin/harvest start -f' {} \;