#!/bin/sh
until [ $(find /opt/harvest/shared -name '*.yaml' | wc -l) -gt 0 ]; do
    echo "Waiting for config file generated by netappsd-worker, sleeping 10 seconds..."
    sleep 10
done

echo "Config file found, starting harvest..."
echo "Use bin/harvest to manage the service"
echo "Logs will be written to /var/log/harvest/"

# Find the config file in ./shared and start poller. The config file is rendered by the netappsd-worker container
exec find /opt/harvest/shared -name '*.yaml' -exec sh -c 'ln -s -f $0 /opt/harvest/harvest.yml && /opt/harvest/bin/harvest start' {} \;