#!/bin/sh
until [ $(find /opt/harvest/shared -name '*.yaml' | wc -l) -gt 0 ]; do
    echo "Waiting for config file generated by netappsd-worker, sleeping 10 seconds..."
    sleep 10
done

echo "Config file found, starting harvest..."
echo "Use bin/harvest to manage the service"
echo "Logs will be written to /var/log/harvest/"

# Config file is rendered by worker sidecar, move it to harvest working directory
find /opt/harvest/shared -type f -name '*yaml' -exec ln -s -f {} /opt/harvest/harvest.yml \;

# Start harvest in the front
exec /opt/harvest/bin/harvest start -f --debug=false
