{{- range $path, $bytes := $.Files.Glob "alerts/storage/*.yaml" }}
{{- with $ }}
{{- if .Values.podMonitor.enabled }}
{{- range $az := required ".Values.global.availability_zones missing" .Values.global.availability_zones }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "netapp-harvest.fullname" $) (trimSuffix ".yaml" $path | replace "/" "-") }}-{{ $az }}
  labels:
    {{- include "netapp-harvest.labels" $ | nindent 4 }}
    type: alerting-rules
    prometheus: {{ printf "storage-metrics-product-%s" $az }}
spec:
  {{ printf "%s" $bytes | nindent 2 }}
---
{{- end }}
{{- else }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "netapp-harvest.fullname" . }}-{{ printf "%s" $path | trimSuffix ".yaml" | replace "/"  "-" }}
  labels:
    {{- include "netapp-harvest.labels" . | nindent 4 }}
    type: alerting-rules
    prometheus: storage
spec:
  {{ printf "%s" $bytes | nindent 2 }}
---
{{- end }}
{{- end }}
{{- end }}

{{- range $path, $bytes := $.Files.Glob "alerts/thanos-metal/*.yaml" }}
{{- with $ }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "netapp-harvest.fullname" . }}-{{ printf "%s" $path | trimSuffix ".yaml" | replace "/"  "-" }}
  labels:
    {{- include "netapp-harvest.labels" . | nindent 4 }}
    type: alerting-rules
    thanos-ruler: metal
    # Disable absent-metrics-operator (AMO) for Thanos-Ruler alerts.
    absent-metrics-operator/disable: "true"
spec:
  {{ printf "%s" $bytes | nindent 2 }}
---
{{- end }}
{{- end }}
