---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metal-maintenance-token-rotate
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-token-rotate
rules:
- apiGroups:
  - "authentication.k8s.io"
  resources:
  - tokenreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metal-maintenance-token-rotate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metal-maintenance-token-rotate
subjects:
- kind: ServiceAccount
  name: metal-maintenance-token-rotate
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metal-maintenance-token-rotate
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  resourceNames:
  - metal-maintenance-operator-controller-manager
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metal-maintenance-token-rotate
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metal-maintenance-token-rotate
subjects:
- kind: ServiceAccount
  name: metal-maintenance-token-rotate
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-viewer
rules:
- apiGroups:
  - readiness.metal.ironcore.dev
  resources:
  - serverwirings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cc:oidc-ias-maintenance-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metal-maintenance-operator-viewer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ if contains "qa-de-" .Values.global.region -}} CC_IAS_CONTROLPLANE_QA_DEVELOPER {{- else -}} CC_IAS_CONTROLPLANE_PROD_DEVELOPER {{- end }}
