---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metal-maintenance-token-rotate
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-token-rotate
rules:
- apiGroups:
  - "authentication.k8s.io"
  resources:
  - tokenreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metal-maintenance-token-rotate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metal-maintenance-token-rotate
subjects:
- kind: ServiceAccount
  name: metal-maintenance-token-rotate
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metal-maintenance-token-rotate
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  resourceNames:
  - metal-maintenance-operator-controller-manager
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metal-maintenance-token-rotate
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metal-maintenance-token-rotate
subjects:
- kind: ServiceAccount
  name: metal-maintenance-token-rotate
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-viewer
rules:
- apiGroups:
  - readiness.metal.ironcore.dev
  resources:
  - serverwirings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cc:oidc-ias-maintenance-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metal-maintenance-operator-viewer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ if contains "qa-de-" .Values.global.region -}} CC_IAS_CONTROLPLANE_QA_DEVELOPER {{- else -}} CC_IAS_CONTROLPLANE_PROD_DEVELOPER {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cc:oidc-ias-maintenance-editor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metal-maintenance-operator-servermaintenance-editor-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ if contains "qa-de-" .Values.global.region -}} CC_IAS_CONTROLPLANE_QA_DEVELOPER {{- else -}} CC_IAS_CONTROLPLANE_PROD_DEVELOPER {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcsettings-admin-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettings
  verbs:
  - '*'
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettings/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcsettings-editor-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettings/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcsettings-viewer-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettings/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcsettingsset-admin-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettingssets
  verbs:
  - '*'
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettingssets/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcsettingsset-editor-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettingssets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettingssets/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcsettingsset-viewer-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettingssets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcsettingssets/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcuser-admin-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcusers
  verbs:
  - '*'
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcusers/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcuser-editor-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcusers/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcuser-viewer-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcusers/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcversion-admin-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcversions
  verbs:
  - '*'
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcversions/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcversion-editor-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcversions/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcversion-viewer-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcversions/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcversionset-admin-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcversionsets
  verbs:
  - '*'
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcversionsets/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcversionset-editor-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcversionsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcversionsets/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-baseboard-bmcversionset-viewer-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcversionsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcversionsets/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-bmcuser-admin-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcusers
  verbs:
  - '*'
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcusers/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-bmcuser-editor-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcusers/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-bmcuser-viewer-role
rules:
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - baseboard.metal.ironcore.dev
  resources:
  - bmcusers/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-console-admin-role
rules:
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles
  verbs:
  - '*'
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-console-editor-role
rules:
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-console-viewer-role
rules:
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-oper-maintenance-servermaintenance-admin-role
rules:
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances
  verbs:
  - '*'
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-ope-maintenance-servermaintenance-editor-role
rules:
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-ope-maintenance-servermaintenance-viewer-role
rules:
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-readiness-serverwiring-admin-role
rules:
- apiGroups:
  - readiness.metal.ironcore.dev
  resources:
  - serverwirings
  verbs:
  - '*'
- apiGroups:
  - readiness.metal.ironcore.dev
  resources:
  - serverwirings/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-readiness-serverwiring-editor-role
rules:
- apiGroups:
  - readiness.metal.ironcore.dev
  resources:
  - serverwirings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - readiness.metal.ironcore.dev
  resources:
  - serverwirings/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-readiness-serverwiring-viewer-role
rules:
- apiGroups:
  - readiness.metal.ironcore.dev
  resources:
  - serverwirings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - readiness.metal.ironcore.dev
  resources:
  - serverwirings/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-servermaintenance-admin-role
rules:
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances
  verbs:
  - '*'
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-servermaintenance-editor-role
rules:
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servermaintenance-editor-role
rules:
- apiGroups:
  - maintenance.metal.ironcore.dev
  - metal.ironcore.dev
  resources:
  - servermaintenances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maintenance.metal.ironcore.dev
  - metal.ironcore.dev
  resources:
  - servermaintenances/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-servermaintenance-viewer-role
rules:
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - maintenance.metal.ironcore.dev
  resources:
  - servermaintenances/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-system-biossettings-admin-role
rules:
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettings
  verbs:
  - '*'
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettings/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-system-biossettings-editor-role
rules:
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettings/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-system-biossettings-viewer-role
rules:
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettings/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-system-biossettingsset-admin-role
rules:
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettingssets
  verbs:
  - '*'
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettingssets/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-system-biossettingsset-editor-role
rules:
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettingssets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettingssets/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-system-biossettingsset-viewer-role
rules:
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettingssets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biossettingssets/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-system-biosversion-admin-role
rules:
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biosversions
  verbs:
  - '*'
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biosversions/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-system-biosversion-editor-role
rules:
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biosversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biosversions/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-system-biosversion-viewer-role
rules:
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biosversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biosversions/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-system-biosversionset-admin-role
rules:
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biosversionsets
  verbs:
  - '*'
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biosversionsets/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-system-biosversionset-editor-role
rules:
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biosversionsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biosversionsets/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-system-biosversionset-viewer-role
rules:
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biosversionsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - system.metal.ironcore.dev
  resources:
  - biosversionsets/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-vendorconsole-console-admin-role
rules:
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles
  verbs:
  - '*'
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-vendorconsole-console-editor-role
rules:
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal-maintenance-operator-vendorconsole-console-viewer-role
rules:
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vendorconsole.metal.ironcore.dev
  resources:
  - consoles/status
  verbs:
  - get
