job:
  schedule: "0 3 * * *"

global:
  region: ""
  alternateRegion: ""

backup:
  container: gardener-secondary-backup
  publicKeyName: pubkey.gpg
  retentionDays: 30
  applicationCredentialId: ""
  applicationCredentialSecret: ""

prometheusRule:
  prometheus: kubernetes
