{{ if .Values.customConfig }}
## RabbitMQ custom config
## Generated by helm template etc/_rabbitmq-custom-config.tpl
## For more information please find helm chart
##     https://github.com/sapcc/helm-charts/tree/master/common/rabbitmq

## For more information about RabbitMQ configuration please find
##     https://www.rabbitmq.com/configure.html

{{- range $k, $v := .Values.customConfig }}
  {{- if not (kindIs "invalid" $v) }}
{{ $k }} = {{ $v }}
  {{- end }}
{{- end }}
{{- end }}
