apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  # For QA regions, override IAS group names:
  # - target:
  #     kind: ClusterRoleBinding
  #     name: cc:oidc-ias-admin
  #   patch: |
  #     - op: replace
  #       path: /subjects/0/name
  #       value: CC_IAS_CONTROLPLANE_QA_ADMIN
  #
  # For this prod environment, base values are correct (PROD groups).
  # No patches needed for rt-eu-de-1.
