owner-info:
  helm-chart-url: 'https://github.com/sapcc/helm-charts/tree/master/prometheus-exporters/github-rate-limit-exporter'
  maintainers:
    - Fabian Ruff
  support-group: containers
  service: github-rate-limit-exporter