rbac:
  enable: false
crd:
  enable: false
metrics:
  enable: false
webhook:
  enable: true
prometheus:
  enable: false
certmanager:
  enable: true
networkPolicy:
  enable: false
controllerManager:
  enable: true
  manager:
    resources:
      limits:
        cpu: "5000m"
        memory: "5120Mi"
    volumes:
    - name: remote-kubeconfig
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readOnly: true
      source:
        secret:
          secretName: metal-operator-remote-kubeconfig
          items:
          - key: token
            path: token
          - key: bundle.crt
            path: ca.crt
  pod:
    labels:
      networking.gardener.cloud/to-dns: allowed
      networking.gardener.cloud/to-private-networks: allowed
      networking.gardener.cloud/to-public-networks: allowed
      networking.gardener.cloud/to-runtime-apiserver: allowed
      networking.resources.gardener.cloud/to-all-istio-ingresses-istio-ingressgateway-tcp-9443: allowed
      networking.resources.gardener.cloud/to-kube-apiserver-tcp-443: allowed
  serviceAccountName: default
  hostNetwork: false
