---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-keystone-pvclaim
  labels:
    ccloud/support-group: identity
    ccloud/service: keystone
spec:
  accessModes:
  - {{ include "volume-claims.accessMode" . }}
  resources:
    requests:
      storage: 10Gi
