---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-manila-pvclaim
  labels:
    ccloud/support-group: compute-storage-api
    ccloud/service: manila
spec:
  accessModes:
  - {{ include "volume-claims.accessMode" . }}
  resources:
    requests:
      storage: 10Gi
