{{- $region := .Values.global.region | required ".Values.global.region missing" }}
{{- $storageRequests := dict
  "eu-de-3" "100Gi"
}}
{{- if hasKey $storageRequests $region }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-nova-cell1-pvc
  labels:
    ccloud/support-group: compute-storage-api
    ccloud/service: nova
spec:
  accessModes:
  - {{ include "volume-claims.accessMode" . }}
  resources:
    requests:
      storage: {{ get $storageRequests $region }}
{{- end }}
