apiVersion: v2
name: keystone-saml-sp-cert-exporter
description: Prometheus exporter for SAML SP signing certificate expiry
version: 0.1.0

maintainers:
  - name: Moutaz Chaara
  - name: Boris Bobrov
  - name: Bernd Kuespert

dependencies:
  - name: prometheus-monitors
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 0.0.2
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 1.0.0
  - name: linkerd-support
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 1.1.1
