apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/ironcore-dev/metal-operator//config/rbac?ref=v0.4.0
namePrefix: metal-operator-
namespace: metal-operator-system
components:
  - ../../../components/clusterrole-conversion
