{{- if .Values.logRouter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: log-router-secret
  namespace: hermes
  labels:
    system: openstack
    service: audit
    component: log-router
type: Opaque
data:
  RABBITMQ_USER: {{ required "missing .Values.logRouter.rabbitmq.user" .Values.logRouter.rabbitmq.user | b64enc }}
  RABBITMQ_PASSWORD: {{ required "missing .Values.logRouter.rabbitmq.password" .Values.logRouter.rabbitmq.password | b64enc }}
  AWS_ACCESS_KEY_ID: {{ required "missing .Values.logRouter.s3.access_key" .Values.logRouter.s3.access_key | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ required "missing .Values.logRouter.s3.secret_key" .Values.logRouter.s3.secret_key | b64enc }}
  OS_PASSWORD: {{ required "missing .Values.hermes.password" .Values.hermes.password | b64enc }}
{{- end }}
