{{- $values := .Values.alerts }}
{{- if $values.enabled }}
{{- range $path, $bytes := .Files.Glob "alerts/*.alerts.tpl" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ printf "apic-exporter-%s" $path | replace "/" "-" | trimSuffix ".tpl" }}
  labels:
    app: apic-exporter
    prometheus: {{ required "$values.prometheus missing" $values.prometheus }}

spec:
{{- with $ }}
{{ tpl (printf "%s" $bytes) . | indent 2 }}
{{- end }}

{{- end }}
{{- end }}
