global:
  tld: example.com
  region: regionOne
  registry: registry.example.com/ccloud
  dockerHubMirror: registry.example.com/dockerhub
  ghcrIoMirror: registry.example.com/ghcr

image_version: v1

auth_url: https://identity.example.com/v3
statsd_hostname: statsd.example.com
alerts:
  prometheus: infra-frontend
passwords:
  target_auth_password: secret

s3_proxy:
  bucket:
    name: content-repo
    s3Endpoint: https://rgw.example.com
    access_key: AKIAEXAMPLE
    secret_key: SECRETEXAMPLE
