{{- if and .Values.objectstore.prysm.rgwSidecarWebhook ( .Values.objectstore.prysm.rgwSidecarWebhook.enabled ) ( .Values.objectstore.prysm.rgwSidecarWebhook.sidecarEnvConfig.enabled ) ( .Values.objectstore.prysm.rgwSidecarWebhook.sidecarEnvConfig.secret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.objectstore.prysm.rgwSidecarWebhook.sidecarEnvConfig.secretName | quote }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- range $key, $val := .Values.objectstore.prysm.rgwSidecarWebhook.sidecarEnvConfig.secret }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}