apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-bin-credential-migrate
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
  labels:
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: keystone
    type: config
data:
  credential_migrate: |
{{ include (print $.Template.BasePath "/bin/_credential_migrate.tpl") . | indent 4 }}
