{{- if and .Values.tls.enabled .Values.global.keystone_external_ip }}
apiVersion: disco.stable.sap.cc/v1
kind: Record
metadata:
  name: {{ .Values.services.public.host }}.{{ .Values.global.region }}.{{ .Values.global.tld }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: A
  record: {{ .Values.global.keystone_external_ip | quote }}
  hosts:
    - {{ .Values.services.public.host }}.{{ .Values.global.region }}.{{ .Values.global.tld }}
  zoneName: {{ .Values.global.region }}.{{ .Values.global.tld }}
{{- end }}
