{{- if .Values.services.ingress.x509.ca }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-x509-ca
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: keystone
    type: x509-ca
data:
  ca.crt: {{ .Values.services.ingress.x509.ca | b64enc }}
{{- end }}
