{{- if .Values.netboxImport }}
apiVersion: v1
kind: Secret
metadata:
  name: netbox-token
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  token: {{ .Values.netboxImport.token | quote }}
{{- end }}
