kind: Ingress
apiVersion: networking.k8s.io/v1

metadata:
  name: aurora
  annotations:
    kubernetes.io/tls-acme: "true"
    dns-manager: "true"
    dns-manager/zone-name: "dashboard-aurora.{{.Values.global.region}}.{{ .Values.global.tld }}"
spec:
  tls:
    - secretName: aurora-ingress-tls
      # prettier-ignore
      hosts: [{{ .Values.ingress.host }}]
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aurora
                port:
                  number: 3000
