{{- $host := .Values.ingress.host | default (printf "dashboard-aurora.%s.%s" .Values.global.region .Values.global.tld) -}}
kind: Ingress
apiVersion: networking.k8s.io/v1

metadata:
  name: aurora
  annotations:
    # ssl cert
    kubernetes.io/tls-acme: "true"
    # create dns CNAME record for dashboard
    disco: "true"
spec:
  tls:
    - secretName: aurora-ingress-tls
      # prettier-ignore
      hosts: ["{{ $host }}"]
  rules:
    - host: "{{ $host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aurora
                port:
                  number: 3000
