{{- if .Values.prPreview.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pr-preview-env
  namespace: aurora-preview
type: Opaque
stringData:
{{- $envList := include (print .Template.BasePath "/_env.tpl") . | fromYamlArray }}
{{- range $envList }}
  {{ .name }}: {{ .value | quote }}
{{- end }}
{{- end }}
