apiVersion: v1
kind: Secret
metadata:
  name: aurora-feedback
type: Opaque
stringData:
  FEEDBACK_RECIPIENT_EMAIL: {{ .Values.feedback_recipient_email | quote }}
  LIMES_MAIL_SERVER_ENDPOINT: {{ .Values.limes_mail_server_endpoint | default (printf "https://limes-campfire.%s.%s/v1/send-email" .Values.global.region .Values.global.tld) | quote }}
  TECHNICAL_USER_NAME: {{ .Values.technical_user_name | quote }}
  TECHNICAL_USER_PASSWORD: {{ .Values.technical_user_password | quote }}
  TECHNICAL_USER_DOMAIN: {{ .Values.technical_user_domain | quote }}
