"context_is_cloud_admin": "role:cloud_image_admin"
"context_is_admin": "rule:context_is_cloud_admin"
"context_is_image_admin": "rule:context_is_admin or role:image_admin"
"context_is_editor": "rule:context_is_image_admin or role:member"
"context_is_viewer": "rule:context_is_editor or role:image_viewer"

"domain_is_iaas": "domain_id in ['bfbe478529c444d3b8397f3a16f82a75']"
"image_is_public": "visibility:public"
"image_is_community": "visibility:community"

"default": "rule:context_is_admin"
"add_image": "rule:context_is_editor"
"delete_image": "rule:context_is_image_admin"
"get_image": "rule:context_is_viewer and (not rule:domain_is_iaas or (not rule:image_is_public and not rule:image_is_community))"
"get_images": "rule:context_is_viewer and (not rule:domain_is_iaas or (not rule:image_is_public and not rule:image_is_community))"
"modify_image": "rule:context_is_image_admin"
"publicize_image": "rule:context_is_cloud_admin or role:image_publicize_admin"
"communitize_image": "rule:context_is_editor"

"download_image": "rule:context_is_viewer"
"upload_image": "rule:context_is_editor"

"delete_image_location": "rule:context_is_editor"
"get_image_location": "rule:context_is_viewer"
"set_image_location": "rule:context_is_editor"

"add_member": "rule:context_is_editor"
"delete_member": "rule:context_is_editor"
"get_member": "rule:context_is_viewer"
"get_members": "rule:context_is_viewer"
"modify_member": "rule:context_is_editor"

"manage_image_cache": "rule:context_is_admin"

"deactivate": "rule:context_is_editor"
"reactivate": "rule:context_is_editor"

"copy_image": "rule:context_is_editor"

"get_metadef_namespace": "rule:context_is_viewer"
"get_metadef_namespaces": "rule:context_is_viewer"
"modify_metadef_namespace": "rule:context_is_editor"
"add_metadef_namespace": "rule:context_is_editor"
"delete_metadef_namespace": "rule:context_is_editor"

"get_metadef_object": "rule:context_is_viewer"
"get_metadef_objects": "rule:context_is_viewer"
"modify_metadef_object": "rule:context_is_editor"
"add_metadef_object": "rule:context_is_editor"
"delete_metadef_object": "rule:context_is_editor"

"list_metadef_resource_types": "rule:context_is_editor"
"get_metadef_resource_type": "rule:context_is_viewer"
"add_metadef_resource_type_association": "rule:context_is_editor"
"remove_metadef_resource_type_association": "rule:context_is_editor"

"get_metadef_property": "rule:context_is_viewer"
"get_metadef_properties": "rule:context_is_viewer"
"modify_metadef_property": "rule:context_is_editor"
"add_metadef_property": "rule:context_is_editor"
"remove_metadef_property": "rule:context_is_editor"

"get_metadef_tag": "rule:context_is_viewer"
"get_metadef_tags": "rule:context_is_viewer"
"modify_metadef_tag": "rule:context_is_editor"
"add_metadef_tag": "rule:context_is_editor"
"delete_metadef_tag": "rule:context_is_editor"
"add_metadef_tags": "rule:context_is_editor"
"delete_metadef_tags": "rule:context_is_editor"

"get_task": "rule:context_is_viewer"
"get_tasks": "rule:context_is_viewer"
"add_task": "rule:context_is_editor"
"modify_task": "rule:context_is_editor"
"tasks_api_access": "role:admin"
