apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-etc
  labels:
    system: openstack
    type: configuration
    component: neutron

data:
  ml2-conf.conf: |
{{ include (print .Template.BasePath "/etc/_ml2-conf.ini.tpl") . | indent 4 }}
  neutron.conf: |
{{ include (print .Template.BasePath "/etc/_neutron.conf.tpl") . | indent 4 }}
  rootwrap.conf: |
{{ include (print .Template.BasePath "/etc/_rootwrap.conf.tpl") . | indent 4 }}
  sudoers: |
{{ include (print .Template.BasePath "/etc/_sudoers.tpl") . | indent 4 }}
  logging.ini: |
{{ include "loggerIni" .Values.logging_sapccsentry | indent 4 }}
{{- if .Values.defaults.network.linuxbridge.deploy_dhcp_agent }}
  dnsmasq.conf: |
{{ include (print .Template.BasePath "/etc/_dnsmasq.conf.tpl") . | indent 4 }}
  dhcp-agent.ini: |
{{ include (print .Template.BasePath "/etc/_dhcp-agent.ini.tpl") . | indent 4 }}
  dhcp.filters: |
{{ include (print .Template.BasePath "/etc/_dhcp.filters.tpl") . | indent 4 }}
  metadata-agent.ini: |
{{ include (print .Template.BasePath "/etc/_metadata-agent.ini.tpl") . | indent 4 }}
  az.conf: |
    {{- if .Values.defaults.availability_zone }}
    [agent]
    availability_zone = {{ .Values.defaults.availability_zone }}
    {{- end }}
    {{- if .Values.defaults.scheduling_disabled }}
    scheduling_disabled = {{ .Values.defaults.scheduling_disabled }}
    {{- end }}
{{- end }}
