apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-network-templates
  labels:
    system: openstack
    type: configuration
    component: neutron
data:
  ovs-uplink.network.j2: |
    {{- .Files.Get "files/ovs-uplink.network.j2" | nindent 4 }}
  ovs-bridge.network.j2: |
    {{- .Files.Get "files/ovs-bridge.network.j2" | nindent 4 }}
