{{- if .Values.biosSettings.enabled }}
{{- range $vendor, $vendorConfig := .Values.machines }}
{{- if $vendorConfig }}

{{/* Vendor filtering */}}
{{- if include "metal-settings.shouldInclude" (dict "item" $vendor "filters" $.Values.biosSettings.filters.vendors) }}
{{- range $entry := $vendorConfig.models }}
{{- if and $entry.clusterTypes $entry.bios $entry.bios.settingsFileName }}
{{- $model := $entry.model }}
{{- $version := $entry.bios.version }}

{{/* Model and Version filtering */}}
{{- if and (include "metal-settings.shouldInclude" (dict "item" $model "filters" $.Values.biosSettings.filters.models)) (include "metal-settings.shouldInclude" (dict "item" $version "filters" $.Values.biosSettings.filters.versions)) }}
{{- range $clusterType := $entry.clusterTypes }}

{{/* ClusterType filtering */}}
{{- if include "metal-settings.shouldInclude" (dict "item" $clusterType "filters" $.Values.biosSettings.filters.clusterTypes) }}
apiVersion: metal.ironcore.dev/v1alpha1
kind: BIOSSettingsSet
metadata:
  name: {{ lower $vendor }}-{{ lower $model }}-{{ lower $clusterType }}
spec:
  serverSelector:
    matchLabels:
      kubernetes.metal.cloud.sap/type: {{ $model }}
      kubernetes.metal.cloud.sap/cluster-type: {{ $clusterType }}
  biosSettingsTemplate:
    serverMaintenancePolicy: OwnerApproval
{{ $.Files.Get (printf "bios_settings/%s" $entry.bios.settingsFileName) | trim | indent 4 }}
    version: {{ $version | quote }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

