{{- if .Values.biosSettings.enabled }}
{{- range $vendor, $vendorConfig := .Values.machines }}
{{- if $vendorConfig }}

{{/* Vendor filtering */}}
{{- if include "metal-settings.shouldInclude" (dict "item" $vendor "filters" $.Values.biosSettings.filters.vendors) }}
{{- range $entryName, $entry := $vendorConfig.models }}
{{- if and $entry.clusterTypes $entry.bios $entry.bios.settingsFileName }}
{{- $model := $entry.model }}
{{- $version := $entry.bios.version }}
{{- $settingsParams := (get $entry.bios "settingsParams") | default dict }}
{{- $serverFilters := (get $settingsParams "serverFilter") | default (dict "included" (list) "excluded" (list)) }}

{{/* Model and Version filtering */}}
{{- if and (include "metal-settings.shouldInclude" (dict "item" $model "filters" $.Values.biosSettings.filters.models)) (include "metal-settings.shouldInclude" (dict "item" $version "filters" $.Values.biosSettings.filters.versions)) }}
{{- range $clusterType := $entry.clusterTypes }}

{{/* ClusterType filtering */}}
{{- if include "metal-settings.shouldInclude" (dict "item" $clusterType "filters" $.Values.biosSettings.filters.clusterTypes) }}
{{- $defaultName := printf "%s-%s-%s" (lower $vendor) (lower $model) (lower $clusterType) }}
{{- $resourceName := (get $settingsParams "setMetadataName") | default $defaultName }}
apiVersion: metal.ironcore.dev/v1alpha1
kind: BIOSSettingsSet
metadata:
  name: {{ $resourceName }}
spec:
  serverSelector:
    matchLabels:
      kubernetes.metal.cloud.sap/type: {{ $model }}
      kubernetes.metal.cloud.sap/cluster-type: {{ $clusterType }}
{{- $serverMatchExpressions := include "metal-settings.serverMatchExpressions" (dict "serverFilters" $serverFilters) }}
{{- if $serverMatchExpressions }}
{{ $serverMatchExpressions | nindent 4 }}
{{- end }}
  biosSettingsTemplate:
    serverMaintenancePolicy: OwnerApproval
{{ $.Files.Get (printf "bios_settings/%s" $entry.bios.settingsFileName) | trim | indent 4 }}
    version: {{ $version | quote }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

