{{- if .Values.bmcSettings.enabled }}
{{- range $vendor, $vendorConfig := .Values.machines }}
{{- if $vendorConfig }}

{{/* Vendor filtering */}}
{{- if include "metal-settings.shouldInclude" (dict "item" $vendor "filters" $.Values.bmcSettings.filters.vendors) }}
{{- range $entry := $vendorConfig.models }}
{{- if and $entry.clusterTypes $entry.bmc $entry.bmc.settingsFileName }}
{{- $model := $entry.model }}
{{- $version := $entry.bmc.version }}

{{/* Model and Version filtering */}}
{{- if and (include "metal-settings.shouldInclude" (dict "item" $model "filters" $.Values.bmcSettings.filters.models)) (include "metal-settings.shouldInclude" (dict "item" $version "filters" $.Values.bmcSettings.filters.versions)) }}
{{- range $clusterType := $entry.clusterTypes }}

{{/* ClusterType filtering */}}
{{- if include "metal-settings.shouldInclude" (dict "item" $clusterType "filters" $.Values.bmcSettings.filters.clusterTypes) }}
apiVersion: metal.ironcore.dev/v1alpha1
kind: BMCSettingsSet
metadata:
  name: {{ lower $vendor }}-{{ lower $model }}-{{ lower $clusterType }}
spec:
  bmcSelector:
    matchLabels:
      kubernetes.metal.cloud.sap/type: {{ $model }}
      kubernetes.metal.cloud.sap/cluster-type: {{ $clusterType }}
{{- if or $.Values.bmcSettings.filters.servers.included $.Values.bmcSettings.filters.servers.excluded }}
    matchExpressions:
{{- if $.Values.bmcSettings.filters.servers.included }}
      - key: kubernetes.metal.cloud.sap/name
        operator: In
        values:
{{- range $.Values.bmcSettings.filters.servers.included }}
          - {{ . | quote }}
{{- end }}
{{- end }}
{{- if $.Values.bmcSettings.filters.servers.excluded }}
      - key: kubernetes.metal.cloud.sap/name
        operator: NotIn
        values:
{{- range $.Values.bmcSettings.filters.servers.excluded }}
          - {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
  bmcSettingsTemplate:
    serverMaintenancePolicy: OwnerApproval
    version: {{ $version | quote }}
{{ tpl ($.Files.Get (printf "bmc_settings/%s" $entry.bmc.settingsFileName)) $ | trim | indent 4 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
