apiVersion: v2
name: seed-ingress-certificate
description: Need to deliver a wildcard TLS certificate to the istio-ingress namespace on seed clusters via Gardener ControllerInstallation.
type: application
version: 0.1.1
