gardener:
  seed:
    ingress:
      domain: ''
    spec:
      dns:
        internal:
          domain: ''

certificate:
  secretName: wildcard-tls
  issuerRef:
    group: certmanager.cloud.sap
    kind: DigicertIssuer
    name: digicert-issuer
  usages:
    - digital signature
    - key encipherment
