owner-info:
  support-group: compute-storage-api
  service: libvirt-kubernetes-exporter
  maintainers:
  - Christian Lehmann
  - Paul Pickhardt
  helm-chart-url: https://github.com/cobaltcore-dev/libvirt-kubernetes-exporter-rehaul
