{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  {{- if .Values.remote.enabled }}
  namespace: {{ .Values.remote.serviceAccount.namespace | default .Release.Namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
