{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: disco-leader-election-rolebinding
  {{- if .Values.remote.enabled }}
  namespace: {{ .Values.remote.role.namespace | default .Release.Namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: disco-leader-election-role
subjects:
- kind: ServiceAccount
  {{- if .Values.remote.enabled }}
  name: {{ .Values.remote.role.subjectName | default .Values.serviceAccount.name }}
  namespace: {{ .Values.remote.role.subjectNamespace | default .Values.remote.role.namespace | default .Release.Namespace }}
  {{- else }}
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
