{{- if .Values.remote.enabled }}
---
apiVersion: resources.gardener.cloud/v1alpha1
kind: ManagedResource
metadata:
  name: {{ .Release.Name }}-crd
spec:
  secretRefs:
  - name: {{ .Release.Name }}-crd
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-crd
type: Opaque
data:
  objects.yaml: {{ .Files.Get "crds/records.disco.stable.sap.cc.yaml" | b64enc }}
---
apiVersion: resources.gardener.cloud/v1alpha1
kind: ManagedResource
metadata:
  name: {{ .Release.Name }}-rbac
spec:
  secretRefs:
  - name: {{ .Release.Name }}-rbac
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rbac
type: Opaque
data:
  objects.yaml: {{ include "disco.shootRBAC" . | b64enc }}
{{- end }}
