{{- if .Values.remote.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-remote-kubeconfig
  labels:
    resources.gardener.cloud/purpose: token-requestor
    resources.gardener.cloud/class: shoot
  annotations:
    serviceaccount.resources.gardener.cloud/name: {{ .Values.serviceAccount.name }}
    serviceaccount.resources.gardener.cloud/namespace: {{ .Values.remote.shootNamespace }}
    serviceaccount.resources.gardener.cloud/inject-ca-bundle: "true"
stringData:
  token: ""
  bundle.crt: ""
{{- end }}
