apiVersion: v1
kind: ServiceAccount
metadata:
  name: ipam-capi-remote-webhook-injector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ipam-capi-remote-webhook-injector
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ipam-capi-remote-webhook-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ipam-capi-remote-webhook-injector
subjects:
  - kind: ServiceAccount
    name: ipam-capi-remote-webhook-injector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipam-capi-remote-webhook-injector
rules:
- verbs:
  - get
  - list
  - watch
  - patch
  apiGroups:
  - resources.gardener.cloud
  resources:
  - managedresources
- verbs:
  - get
  - update
  - patch
  apiGroups:
  - ""
  resources:
  - secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ipam-capi-remote-webhook-injector
subjects:
- kind: ServiceAccount
  name: ipam-capi-remote-webhook-injector
  namespace: '{{ .Release.Namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ipam-capi-remote-webhook-injector
