global:
  region: xx-yy-1
  registry: registry.example.com
  vaultBaseURL: vault.example.com

concourse:
  secrets:
    postgresUser: test
    postgresPassword: test
    encryptionKey: 0123456789abcdef0123456789abcdef
    localUsers: "admin:test"

webhookBroadcaster:
  auth:
    username: test
    password: test
