awsCredentials:
  principal: foo
  accessKeyID: Zm9v
  secretAccessKey: YmFy
  region: dGhlcmU=

encryptionRotation:
  enabled: true
  schedule: "0 */8 * * *"
  image:
    repository: keppel.global.cloud.sap/ccloud/mjolnir
    tag: v0.1.0
  rotationDays: 90
  secretLength: 32
  nodesCount: 3
  resources: "secrets.v1.,configmaps.v1."
  capiNamespace: capi-test
  kcpName: test-cluster
  secretName: etcd-encryption-config
