global:
  region: qa-de-1
  alternateRegion: eu-de-1
  registry: keppel.eu-de-1.cloud.sap/ccloud

backup:
  applicationCredentialId: test-credential-id
  applicationCredentialSecret: test-credential-secret
