{{- define "keystone.shibboleth2.xml" -}}
<SPConfig xmlns="urn:mace:shibboleth:3.0:native:sp:config"
    xmlns:conf="urn:mace:shibboleth:3.0:native:sp:config"
    clockSkew="180">

    <!--
      Shibboleth SP configuration for Keystone SAML 2.0 federation.
      Generated by Helm from values in federation.saml.
    -->

    <OutOfProcess tranLogFormat="%u|%s|%IDP|%i|%ac|%t|%attr|%n|%b|%E|%S|%SS|%L|%UA|%a">
        <Extensions>
            <Library path="memcache-store.so" fatal="false"/>
        </Extensions>
    </OutOfProcess>

    <InProcess>
        <ISAPI normalizeRequest="true" safeHeaderNames="true"/>
    </InProcess>

    {{- $memcachedHost := "" }}
    {{- if $.Values.memcached.host }}
    {{- $memcachedHost = printf "%s:%s" $.Values.memcached.host ($.Values.memcached.port | default "11211" | toString) }}
    {{- else }}
    {{- $memcachedHost = printf "%s-memcached.%s.svc:%s" $.Release.Name $.Release.Namespace ($.Values.memcached.port | default "11211" | toString) }}
    {{- end }}

    <!-- Shared session and replay cache via memcached for multi-pod consistency -->
    <StorageService type="MEMCACHE" id="mc" prefix="shib_" buildMap="1">
        <Hosts>{{ $memcachedHost }}</Hosts>
    </StorageService>

    <SessionCache type="StorageService" StorageService="mc" cacheAllowance="900"/>
    <ReplayCache StorageService="mc"/>
    <ArtifactMap StorageService="mc" artifactTTL="180"/>

    <RequestMapper type="Native">
        <RequestMap>
            <Host name="{{ $.Values.services.public.host }}.{{ $.Values.global.region }}.{{ $.Values.global.tld }}">
                {{- range $tenant := $.Values.federation.saml.idp.tenants }}
                <Path name="v3/OS-FEDERATION/identity_providers/{{ $tenant.name }}/protocols/mapped/auth"
                      authType="shibboleth" requireSession="true" entityID="{{ $tenant.entityId }}"/>
                <Path name="v3/auth/OS-FEDERATION/identity_providers/{{ $tenant.name }}/protocols/mapped/websso"
                      authType="shibboleth" requireSession="true" entityID="{{ $tenant.entityId }}"/>
                {{- end }}
            </Host>
        </RequestMap>
    </RequestMapper>

    <ApplicationDefaults entityID="{{ $.Values.federation.saml.sp.entityId }}"
                         REMOTE_USER="eppn subject-id pairwise-id persistent-id"
                         signing="{{ if $.Values.federation.saml.shibboleth.signAuthnRequests }}true{{ else }}false{{ end }}"
                         encryption="{{ if $.Values.federation.saml.shibboleth.encryptionEnabled }}true{{ else }}false{{ end }}">

        <Sessions lifetime="{{ $.Values.federation.saml.shibboleth.sessionLifetime | default 28800 }}"
                  timeout="3600"
                  relayState="ss:mc"
                  checkAddress="false"
                  handlerSSL="true"
                  cookieProps="https"
                  redirectLimit="exact">

            <SSO>SAML2</SSO>

            <Logout>Local</Logout>

            <Handler type="MetadataGenerator" Location="/Metadata" signing="false"/>
            <Handler type="Status" Location="/Status" acl="127.0.0.1 ::1"/>
            <Handler type="Session" Location="/Session" showAttributeValues="false"/>
        </Sessions>

        <Errors supportContact="root@localhost" helpLocation="/about.html" styleSheet="/shibboleth-sp/main.css"/>

        {{- range $tenant := $.Values.federation.saml.idp.tenants }}
        <!-- IdP metadata for tenant: {{ $tenant.name }} -->
        <MetadataProvider type="XML"
            path="/etc/shibboleth/metadata/{{ $tenant.name }}-metadata.xml"
            reloadChanges="true"/>
        {{- end }}

        <AttributeExtractor type="XML" validate="true" reloadChanges="true"
            path="/etc/shibboleth/attribute-map.xml"/>

        <AttributeFilter type="XML" validate="true"
            path="/etc/shibboleth/attribute-policy.xml"/>

        <CredentialResolver type="File"
            key="/etc/shibboleth/sp-keys/sp-key.pem"
            certificate="/etc/shibboleth/sp-keys/sp-cert.pem"/>

    </ApplicationDefaults>

    <SecurityPolicyProvider type="XML" validate="true"
        path="/etc/shibboleth/security-policy.xml"/>

    <ProtocolProvider type="XML" validate="true" reloadChanges="false"
        path="protocols.xml"/>

</SPConfig>
{{- end -}}
