apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      url: https://metal-operator-webhook-service:443/validate-metal-ironcore-dev-v1alpha1-biossettings
    failurePolicy: Fail
    name: vbiossettings-v1alpha1.kb.io
    rules:
      - apiGroups:
          - metal.ironcore.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - biossettings
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      url: https://metal-operator-webhook-service:443/validate-metal-ironcore-dev-v1alpha1-biosversion
    failurePolicy: Fail
    name: vbiosversion-v1alpha1.kb.io
    rules:
      - apiGroups:
          - metal.ironcore.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - biosversions
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      url: https://metal-operator-webhook-service:443/validate-metal-ironcore-dev-v1alpha1-bmcsecret
    failurePolicy: Fail
    name: vbmcsecret-v1alpha1.kb.io
    rules:
      - apiGroups:
          - metal.ironcore.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - bmcsecrets
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      url: https://metal-operator-webhook-service:443/validate-metal-ironcore-dev-v1alpha1-bmcsettings
    failurePolicy: Fail
    name: vbmcsettings-v1alpha1.kb.io
    rules:
      - apiGroups:
          - metal.ironcore.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - bmcsettings
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      url: https://metal-operator-webhook-service:443/validate-metal-ironcore-dev-v1alpha1-bmcversion
    failurePolicy: Fail
    name: vbmcversion-v1alpha1.kb.io
    rules:
      - apiGroups:
          - metal.ironcore.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - bmcversions
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      url: https://metal-operator-webhook-service:443/validate-metal-ironcore-dev-v1alpha1-endpoint
    failurePolicy: Fail
    name: vendpoint-v1alpha1.kb.io
    rules:
      - apiGroups:
          - metal.ironcore.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - endpoints
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      url: https://metal-operator-webhook-service:443/validate-metal-ironcore-dev-v1alpha1-server
    failurePolicy: Fail
    name: vserver-v1alpha1.kb.io
    rules:
      - apiGroups:
          - metal.ironcore.dev
        apiVersions:
          - v1alpha1
        operations:
          - DELETE
        resources:
          - servers
    sideEffects: None
