USE mysql;
SET @user := '${MARIADB_MONITORING_USER}';
SET @host := '%';
SET @pass := '${MARIADB_MONITORING_PASSWORD}';
SET @connlimit := '${MARIADB_MONITORING_CONNECTION_LIMIT}';
SET @createuser := CONCAT("CREATE OR REPLACE USER ", QUOTE(@user), "@", QUOTE(@host), " IDENTIFIED BY ", QUOTE(@pass), "WITH MAX_USER_CONNECTIONS ", @connlimit);
SET @grantperms := CONCAT("GRANT PROCESS, REPLICATION CLIENT, SLAVE MONITOR ON *.* TO ", QUOTE(@user), "@", QUOTE(@host));
PREPARE stmt_createuser FROM @createuser;
PREPARE stmt_grantperms FROM @grantperms;
EXECUTE stmt_createuser;
EXECUTE stmt_grantperms;
DROP PREPARE stmt_createuser;
DROP PREPARE stmt_grantperms;
SET @user := '${MARIADB_MONITORING_USER}';
SET @host := '127.0.0.1';
SET @pass := '${MARIADB_MONITORING_PASSWORD}';
SET @createuser := CONCAT("CREATE OR REPLACE USER ", QUOTE(@user), "@", QUOTE(@host), " IDENTIFIED BY ", QUOTE(@pass), "WITH MAX_USER_CONNECTIONS ", @connlimit);
SET @grantperms := CONCAT("GRANT PROCESS, REPLICATION CLIENT, SLAVE MONITOR ON *.* TO ", QUOTE(@user), "@", QUOTE(@host));
PREPARE stmt_createuser FROM @createuser;
PREPARE stmt_grantperms FROM @grantperms;
EXECUTE stmt_createuser;
EXECUTE stmt_grantperms;
DROP PREPARE stmt_createuser;
DROP PREPARE stmt_grantperms;
SET @user := '${MARIADB_MONITORING_USER}';
SET @host := '::1';
SET @pass := '${MARIADB_MONITORING_PASSWORD}';
SET @createuser := CONCAT("CREATE OR REPLACE USER ", QUOTE(@user), "@", QUOTE(@host), " IDENTIFIED BY ", QUOTE(@pass), "WITH MAX_USER_CONNECTIONS ", @connlimit);
SET @grantperms := CONCAT("GRANT PROCESS, REPLICATION CLIENT, SLAVE MONITOR ON *.* TO ", QUOTE(@user), "@", QUOTE(@host));
PREPARE stmt_createuser FROM @createuser;
PREPARE stmt_grantperms FROM @grantperms;
EXECUTE stmt_createuser;
EXECUTE stmt_grantperms;
DROP PREPARE stmt_createuser;
DROP PREPARE stmt_grantperms;
