USE mysql;
SET @user := 'root';
SET @host := '%';
SET @pass := '${MARIADB_ROOT_PASSWORD}';
SET @createuser := CONCAT("CREATE USER ", QUOTE(@user), "@", QUOTE(@host), " IDENTIFIED BY ", QUOTE(@pass));
SET @grantperms := CONCAT("GRANT ALL ON *.* TO ", QUOTE(@user), "@", QUOTE(@host), " WITH GRANT OPTION");
PREPARE stmt_createuser FROM @createuser;
PREPARE stmt_grantperms FROM @grantperms;
EXECUTE stmt_createuser;
EXECUTE stmt_grantperms;
DROP PREPARE stmt_createuser;
DROP PREPARE stmt_grantperms;
SET @user := 'root';
SET @host := '127.0.0.1';
SET @pass := '${MARIADB_ROOT_PASSWORD}';
SET @createuser := CONCAT("ALTER USER ", QUOTE(@user), "@", QUOTE(@host), " IDENTIFIED BY ", QUOTE(@pass));
SET @grantperms := CONCAT("GRANT ALL ON *.* TO ", QUOTE(@user), "@", QUOTE(@host), " WITH GRANT OPTION");
PREPARE stmt_createuser FROM @createuser;
PREPARE stmt_grantperms FROM @grantperms;
EXECUTE stmt_createuser;
EXECUTE stmt_grantperms;
DROP PREPARE stmt_createuser;
DROP PREPARE stmt_grantperms;
SET @user := 'root';
SET @host := '::1';
SET @pass := '${MARIADB_ROOT_PASSWORD}';
SET @createuser := CONCAT("ALTER USER ", QUOTE(@user), "@", QUOTE(@host), " IDENTIFIED BY ", QUOTE(@pass));
SET @grantperms := CONCAT("GRANT ALL ON *.* TO ", QUOTE(@user), "@", QUOTE(@host), " WITH GRANT OPTION");
PREPARE stmt_createuser FROM @createuser;
PREPARE stmt_grantperms FROM @grantperms;
EXECUTE stmt_createuser;
EXECUTE stmt_grantperms;
DROP PREPARE stmt_createuser;
DROP PREPARE stmt_grantperms;
SET @user := 'root';
SET @host := "${HOSTNAME}";
SET @pass := '${MARIADB_ROOT_PASSWORD}';
SET @createuser := CONCAT("ALTER USER ", QUOTE(@user), "@", QUOTE(@host), " IDENTIFIED BY ", QUOTE(@pass));
SET @grantperms := CONCAT("GRANT ALL ON *.* TO ", QUOTE(@user), "@", QUOTE(@host), " WITH GRANT OPTION");
PREPARE stmt_createuser FROM @createuser;
PREPARE stmt_grantperms FROM @grantperms;
EXECUTE stmt_createuser;
EXECUTE stmt_grantperms;
DROP PREPARE stmt_createuser;
DROP PREPARE stmt_grantperms;
