apiVersion: v2
name: gatekeeper-policies
description: Holding bag for Gatekeeper policy code (not deployable on its own, only intended to be imported by other charts)
version: 1.0.0
icon: https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/logo/gatekeeper-horizontal-color.png
sources:
  - https://github.com/sapcc/helm-charts/tree/master/common/gatekeeper-policies
