{{- if $.Values.unbound.dnstap.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-hec-secrets
type: Opaque
data:
  hec_splunk_url: {{ required ".Values.unbound.dnstap.hec_splunk_url is required if dnstap is enabled." $.Values.unbound.dnstap.hec_splunk_url | b64enc }}
  hec_splunk_token: {{ required ".Values.unbound.dnstap.hec_splunk_token is required if dnstap is enabled." $.Values.unbound.dnstap.hec_splunk_token | b64enc }}
{{- end }}
