{
 "title": "Concourse Scaleout",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": "label_values(concourse_scheduling_full_duration_seconds_total, pipeline)"
   }
  ]
 },
 "panels": [
  {
   "title": "Git-Proxy requests per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count[5m]))*60",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(request_duration_seconds_count{code=\"500\"}[5m]))*60",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Git-Proxy 95% request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{code=\"200\"}[5m])) by (pod, le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Git-Proxy requests inflight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "request_inflight", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Pipeline scheduling full duration",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "max(rate(concourse_scheduling_full_duration_seconds_total{pipeline=~\"$pipeline\"}[5m])*10) without (instance)",
     "legendFormat": "{{pipeline}}"
    },
    {}
   ]
  },
  {
   "title": "Loading versions duration",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "max(rate(concourse_scheduling_loading_duration_seconds_total{pipeline=~\"$pipeline\"}[5m])*10) without (instance)",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max(concourse_workers_containers) without (instance))",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "Containers per worker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_workers_containers) without (instance)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max(concourse_workers_volumes) without (instance))",
     "legendFormat": "Volumes"
    }
   ]
  },
  {
   "title": "Volumes per worker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(concourse_workers_volumes) without (instance)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_name=\"concourse-web\"}",
     "legendFormat": "web {{instance}}"
    }
   ]
  },
  {
   "title": "Builds per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(concourse_builds_succeeded_total[5m])*60) without (instance)",
     "legendFormat": "finished"
    },
    {
     "expr": "sum(rate(concourse_builds_failed_total[5m])*60) without (instance)",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(rate(concourse_builds_aborted_total[5m])*60) without (instance)",
     "legendFormat": "aborted"
    },
    {
     "expr": "sum(rate(concourse_builds_errored_total[5m])*60) without (instance)",
     "legendFormat": "errored"
    },
    {
     "expr": "sum(rate(concourse_builds_started_total[5m])*60) without (instance)",
     "legendFormat": "started"
    }
   ]
  },
  {
   "title": "Database connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_db_connections", "legendFormat": "{{dbname}} {{instance}}" }
   ]
  },
  {
   "title": "Database queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(concourse_db_queries_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}