FROM keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/library/alpine:3.22

RUN apk add --no-cache bash iproute2

LABEL source_repository="https://github.com/sapcc/helm-charts/tree/master/system/bridge-attach"
LABEL maintainer="Marian Schwarz"
