enabled: true

# Interface to attach to the bridge.
interface: eth1

# Bridge the interface should become a member of.
bridge: br0

images:
  bridgeAttach:
    image: keppel.global.cloud.sap/ccloud/bridge-attach
    tag: "latest"

resources:
  limits:
    cpu: 50m
    memory: 32Mi
  requests:
    cpu: 10m
    memory: 16Mi

nodeSelector: {}

tolerations:
  - operator: Exists

affinity: {}
