apiVersion: v2
name: kvm-ha-agent-umbrella
description: Umbrella Helm Chart for KVM HA Agent
type: application

version: 0.1.2
appVersion: "0.2.0"

dependencies:
- name: kvm-ha-agent
  version: '0.1.6'
  repository: "oci://keppel.eu-de-1.cloud.sap/ccloud-helm"
- name: owner-info
  repository: "oci://keppel.eu-de-1.cloud.sap/ccloud-helm"
  version: '>= 0.0.0'
