apiVersion: v1
kind: Secret
metadata:
  name: github-app-secret-sci
  namespace: {{ .Release.Namespace }}
  labels:
    greenhouse.sap/owned-by: containers
type: Opaque
data:
  ca.crt: {{ .Values.kubeExtensions.githubApp.caCRT | b64enc  }}
  githubAppBaseURL: {{ .Values.kubeExtensions.githubApp.baseURL | b64enc  }}
  githubAppID: {{ .Values.kubeExtensions.githubApp.appID | b64enc  }}
  githubAppInstallationID: {{ "9426" | b64enc  }}
  githubAppPrivateKey: {{ .Values.kubeExtensions.githubApp.privateKey | b64enc  }}
