{{- range $cluster := .Values.clusters }}
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: {{ $cluster.name }}
  namespace: {{ $cluster.namespace }}
  labels:
    cluster.x-k8s.io/cluster-name: {{ $cluster.name }}
spec:
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: kcp-{{ $cluster.name }}
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: IroncoreMetalCluster
    name: metalcluster-{{ $cluster.name }}
  clusterNetwork:
    serviceDomain: cluster.local
    pods:
      cidrBlocks:
      - {{ $.Values.controlplane.podSubnet }}
    services:
      cidrBlocks:
      - {{ $.Values.controlplane.serviceSubnet }}
{{- end }}
