{{- range $cluster := .Values.clusters }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IroncoreMetalMachineTemplate
metadata:
  name: controlplane-{{ $cluster.name }}
  namespace: {{ $cluster.namespace }}
spec:
  template:
    spec:
      serverSelector:
        matchLabels:
          kubernetes.metal.cloud.sap/cluster: {{ $cluster.name }}
          kubernetes.metal.cloud.sap/role: runtime-controlplane
      image: {{ $.Values.machineTemplate.image }}
      metadata:
{{ toYaml $.Values.machineTemplate.metadata | indent 8 }}
      ipamConfig:
      - metadataKey: bond
        ipamRef:
          apiGroup: ipam.cluster.x-k8s.io
          kind: GlobalInClusterIPPool
          name: globalinclusterippool-{{ $cluster.name }}
{{- end }}
