apiVersion: v2
name: metaldhcp
description: coredhcp-based OOB DHCP server for bare-metal discovery networks
type: application
version: 0.2.0
appVersion: "0.0.1"
dependencies:
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: '>= 0.0.0'
