{{- if .Values.netapp.enable_watcher }}
apiVersion: kvm.cloud.sap/v1alpha
kind: NetappFilerWatcher
metadata:
  labels:
    app.kubernetes.io/name: kvm-cinder-netapp-operator
    app.kubernetes.io/managed-by: kustomize
  name: netappfilerwatcher
spec: 
  region: {{ .Values.global.region }}
  filerexpr: {{ .Values.netapp.filerexpr }}
{{- end}}
