apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: sap-flavor-seed
spec:
  requires:
  - monsoon3/nova-flavor-seed
  flavors:
{{- range $name, $values := .Values.flavors.untemplated }}
  - name: {{ $name }}
    {{- toYaml $values | nindent 4 }}
{{- end }}
  ### HANA flavors
{{- if .Values.use_hana_exclusive }}
{{ include (print .Template.BasePath "/_flavors_hana_exclusive.tpl") . | indent 2 }}
{{- else }}
{{ include (print .Template.BasePath "/_flavors_hana_no_exclusive.tpl") . | indent 2 }}
{{- end }}
