owner-info:
  support-group: containers
  service: content-repo
  maintainers:
    - Stefan Majewsky
    - Sandro Jäckel
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/openstack/content-repo-seed

content_repo:
  service_password: null        # provided by regional values.yaml
