{{- if .Values.plutono.centralMonitoring.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: plutono-inline-datasources
type: Opaque
stringData:
  datasources.yaml: |
    apiVersion: 1
    datasources:
{{- if .Values.plutono.centralMonitoring.datasources }}
{{ toYaml .Values.plutono.centralMonitoring.datasources | nindent 6 }}
{{- else }}
      []
{{- end }}
{{- end }}
