apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/ironcore-dev/metal-operator//config/manager?ref=v0.4.0
namePrefix: metal-operator-
namespace: metal-operator-system
components:
  - ../../components/webhook-injector
patches:
  - path: manager-config-patch.yaml
    target:
      kind: Deployment
      name: controller-manager
configMapGenerator:
  - name: webhook-config
    files:
      - webhooks-input.yaml
    options:
      disableNameSuffixHash: true
