apiVersion: v2
name: netapp-monitoring
description: A Helm chart for harvest.io - https://github.com/NetApp/harvest
type: application
version: 1.0.0

# * Release tag of Harvest - https://github.com/NetApp/harvest/releases
appVersion: "25.11.0"
maintainers:
  - name: Ganesh Kugulakrishnan
  - name: Chandrakanth Renduchintala 