apiVersion: greenhouse.sap/v1alpha1
kind: PluginDefinition
metadata:
  name: netapp-monitoring
spec:
  version: 1.0.2
  displayName: NetApp Monitoring
  description: Helm chart for NetApp storage monitoring using harvest.io
  helmChart:
    name: netapp-monitoring
    repository: https://github.com/sapcc/helm-charts/tree/feat/storage-netapp-monitoring-chart/prometheus-exporters/netapp-monitoring
    version: 1.0.2
  options:
    - name: harvest.image
      description: Harvest container image
      required: false
      type: string
    - name: harvest.tag
      description: Harvest container image tag
      required: false
      type: string
    - name: netappsd.enabled
      description: Enable NetApp service discovery
      required: false
      default: false
      type: bool
    - name: netappsd.image.repository
      description: NetApp SD container image repository
      required: false
      type: string
    - name: netappsd.image.tag
      description: NetApp SD container image tag
      required: false
      type: string
    - name: netappsd.region
      description: Region for NetApp service discovery
      required: false
      type: string
    - name: netappsd.netapp_exporter_user
      description: NetApp exporter username
      required: false
      type: secret
    - name: netappsd.netapp_exporter_password
      description: NetApp exporter password
      required: false
      type: secret
    - name: netappsd.netbox_api_token
      description: Netbox API token
      required: false
      type: secret
    - name: netappsd.netbox_host
      description: Netbox host URL
      required: false
      type: string
    - name: apps
      description: "Map of apps to enable (e.g. cinder, manila, apod)"
      required: false
      type: map