---
harvest:
  image:
  tag:
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:
  securityContext:
    runAsNonRoot:
    runAsUser:
    runAsGroup:
    allowPrivilegeEscalation:
    readOnlyRootFilesystem:
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type:

auth:
  auth_style:

exporters:
  prometheus:
    exporter:
    port:

defaults:
  collectors: []
  use_insecure_tls:
  exporters: []

netappsd:
  enabled: false
  image:
    repository:
    tag:
    pullPolicy:
  region: ""
  ports:
    metrics:
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:
  netapp_exporter_user: ""
  netapp_exporter_password: ""
  netbox_api_token: ""
  netbox_host: ""
  credentials_file:
  credentials_secret:

apps: {}

finalizers: []

owner-info:
  support-group: storage
  service: netapp-monitoring
  maintainers:
    - Ganesh Kugulakrishnan
    - Chandrakanth Renduchintala
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/feat/storage-netapp-monitoring-chart/prometheus-exporters/netapp-monitoring