{{- $regions := list -}}
{{- range $key, $cluster := .Values.kvmShoots -}}
  {{- $regions = append $regions $cluster.region -}}
{{- end -}}
{{- $uniqueRegions := $regions | uniq | sortAlpha -}}
{{- range $uniqueRegions }}
{{- if (ne $.Release.Namespace "garden") }}
---
apiVersion: security.gardener.cloud/v1alpha1
kind: CredentialsBinding
metadata:
  name: metal-wi-{{ . }}
provider:
  type: ironcore-metal
credentialsRef:
  apiVersion: security.gardener.cloud/v1alpha1
  kind: WorkloadIdentity
  name: metal-wi
  namespace: garden
{{- end }}
{{- end }}
