global:
  accessControlAllowOrigin: '*'
  region: regionOne
  domain: evil.corp
  registry: keppel.regionOne.cloud
  registryAlternateRegion: keppel.regionTwo.cloud
  dockerHubMirror: myRegistry/dockerhub
  dockerHubMirrorAlternateRegion: myRegistry/dockerhubalternate
  tld: regionOne.cloud
  domain_seeds:
    customer_domains: [bar, foo, baz]
    customer_domains_without_support_projects: [baz]

  master_password: topSecret
  nova_service_password: topSecret
  availability_zones:
    - foo
    - bar
  nova_metadata_secret: topSecretWouldBuyAgain

imageVersion: myTag
imageVersionVspc: vspc-latest-tag
imageVersionConsoleMks: console-mks-tag

mariadb:
  root_password: rootroot
  enabled: false
  backup:
    enabled: false
  backup_v2:
    enabled: false
  users:
    nova:
      name: nova
      password: password

dbPassword: top-secret
cell0dbPassword: very-secret
apidbPassword: much-secret

mariadb_api:
  enabled: false
  backup:
    enabled: false
  backup_v2:
    enabled: false
  users:
    nova_api:
      name: nova_api
      password: password

rabbitmq:
  users:
    admin:
      password: adminadmin
    default:
      password: defaultdefault
  metrics:
    password: metricsmetrics

cors:
  enabled: true
  additional_allow_headers: 'X-No-Real-Header'

utils:
  cors:
    allowed_origin: 'https://test.domain'

rate_limit:
  enabled: false
  rate_limit_by: target_project_id
  max_sleep_time_seconds: 0
  log_sleep_time_seconds: 10
  backend_timeout_seconds: 1
  whitelist:
    - Default/service
    - Default/admin
    - tempest/performance-testing
    - ccadmin/cloud_admin
    - ccadmin/master
  whitelist_users: null
  blacklist: null
  blacklist_users: null
  groups:
    write:
      - delete
      - update
  rates:
    default:
      servers:
        - action: read/list
          limit: 100r/m
        - action: create
          limit: 100r/m
      servers/server:
        - action: read/list
          limit: 100r/m
        - action: write
          limit: 100r/m
      servers/*/migrations:
        - action: read/list
          limit: 100r/m
      servers/*/migrations/migration:
        - action: read/list
          limit: 100r/m
      servers/*/action:
        - action: create
          limit: 100r/m
      flavors:
        - action: read/list
          limit: 100r/m
        - action: create
          limit: 100r/m
      flavors/flavor:
        - action: read/list
          limit: 100r/m
        - action: write
          limit: 100r/m
      os-keypairs:
        - action: read/list
          limit: 100r/m
        - action: create
          limit: 100r/m
      os-aggregates:
        - action: read/list
          limit: 100r/m
        - action: create
          limit: 100r/m
      os-aggregates/os-aggregate:
        - action: read/list
          limit: 100r/m
        - action: write
          limit: 100r/m
      os-availability-zone:
        - action: read/list
          limit: 100r/m
      os-hypervisors:
        - action: read/list
          limit: 100r/m
      os-server-groups:
        - action: read/list
          limit: 100r/m
        - action: write
          limit: 100r/m
      os-server-groups/os-server-group:
        - action: read/list
          limit: 100r/m
