{{/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company

SPDX-License-Identifier: Apache-2.0
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "persephone-liquid-apiserver.fullname" . }}-policy
  labels:
    {{- include "persephone-liquid-apiserver.labels" . | nindent 4 }}
data:
  policy.json: {{ .Values.liquidPolicy.rules | quote }}
