USE mysql;
SET @host := '${DB_HOST}';
SET @user := '${DB_USERNAME}';
SET @pass := '${DB_PASS}';
SET @authplugin := '${DB_AUTHPLUGIN}';
SET @rolename := '${DB_ROLE}';
SET @admingrant := '${DB_ADMIN_GRANT}';
SET @connlimit := '${CONN_LIMIT}';
SET @createuser := CONCAT("CREATE USER IF NOT EXISTS ", QUOTE(@user), "@", QUOTE(@host), " IDENTIFIED VIA ", @authplugin, " USING PASSWORD(", QUOTE(@pass), ") WITH MAX_USER_CONNECTIONS ", @connlimit);
SET @alteruser := CONCAT("ALTER USER IF EXISTS ", QUOTE(@user), "@", QUOTE(@host), " IDENTIFIED VIA ", @authplugin, " USING PASSWORD(", QUOTE(@pass), ") WITH MAX_USER_CONNECTIONS ", @connlimit);
SET @grantprivs := CONCAT("GRANT ", @rolename, " TO ", QUOTE(@user), "@", QUOTE(@host), @admingrant);
PREPARE stmt_runcode FROM @createuser;
EXECUTE stmt_runcode;
PREPARE stmt_runcode FROM @alteruser;
EXECUTE stmt_runcode;
DROP PREPARE stmt_runcode;
PREPARE stmt_runcode FROM @grantprivs;
EXECUTE stmt_runcode;
DROP PREPARE stmt_runcode;
FLUSH USER_VARIABLES;