USE mysql;
SET @rolename := '${DB_ROLE}';
SET @roleprivs := '${DB_ROLE_PRIVS}';
SET @roleobj := '${DB_ROLE_OBJ}';
SET @rolegrant := '${DB_ROLE_GRANT}';
SET @createrole := CONCAT("CREATE OR REPLACE ROLE ", QUOTE(@rolename));
SET @setrole := CONCAT("GRANT ", @roleprivs, " ON ", @roleobj, " TO ", QUOTE(@rolename), " ", @rolegrant);
PREPARE stmt_runcode FROM @createrole;
EXECUTE stmt_runcode;
DROP PREPARE stmt_runcode;
PREPARE stmt_runcode FROM @setrole;
EXECUTE stmt_runcode;
DROP PREPARE stmt_runcode;
FLUSH USER_VARIABLES;
