owner-info:
  helm-chart-url: 'https://github.com/sapcc/helm-charts/tree/master/prometheus-exporters/github-rate-limits-exporter'
  maintainers:
    - Fabian Ruff
  support-group: containers
  service: github-rate-limits-exporter

ccee-bot:
  exporter:
    image: keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/theodore86/prometheus-gh-rate-limit-exporter
    # The upstream chart botched 0.10.0 chart release still have 0.7.6 references as default in new version
    # we might be able to drop the specific tag and just use the default tag from the upstream chart 
    tag: "v0.10.0"
sapcc-bot:
  exporter:
    image: keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/theodore86/prometheus-gh-rate-limit-exporter
    tag: "v0.10.0"