apiVersion: v1
kind: Secret
metadata:
  name: {{ include "os-user-rotate.fullname" . }}
  labels:
    k8s-app: os-user-rotate
type: Opaque
data:
  username: {{ include "os-user-rotate.usernameResolved" . | trim | b64enc }}
  password: {{ include "os-user-rotate.passwordResolved" . | trim | b64enc }}
