{{- if .Values.keppel.anycast_domain_name }}
apiVersion: v1
kind: ConfigMap

metadata:
  name: keppel-anycast-nginx

data:
  proxy.conf.template: |
    {{- .Files.Get "files/proxy.conf.template" | nindent 4 }}
{{- end }}
