kind: Deployment
apiVersion: apps/v1

metadata:
  name: keppel-liquid-api
  annotations:
    secret.reloader.stakater.com/reload: keppel-issuer-key,keppel-keys,keppel-secret

spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: keppel-liquid-api
  template:
    metadata:
      labels:
        name: keppel-liquid-api
      annotations:
        checksum/configmap: {{ include "keppel/templates/configmap.yaml" . | sha256sum }}
        checksum/secret: {{ include "keppel/templates/secret.yaml" . | sha256sum }}
        checksum/secret-keys: {{ include "keppel/templates/secret-keys.yaml" . | sha256sum }}
        kubectl.kubernetes.io/default-container: liquid-api
    spec:
      volumes:
        - name: config
          configMap:
            name: keppel
        - name: keys
          secret:
            secretName: keppel-keys
        - name: issuer-key
          secret:
            secretName: keppel-issuer-key
      containers:
        - name: liquid-api
          image: {{include "keppel_image" .}}
          imagePullPolicy: IfNotPresent
          args: [ server, liquidapi ]
          env: {{ include "keppel_environment" $ | indent 12 }}
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /etc/keppel
              name: config
            - mountPath: /etc/keppel-keys
              name: keys
            - mountPath: /etc/keppel-issuer-key
              name: issuer-key
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            timeoutSeconds: 10
            periodSeconds: 60
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            timeoutSeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
