{{- if .Values.keppel.anycast_domain_name }}
kind: Deployment
apiVersion: apps/v1

metadata:
  name: keppel-anycast-nginx

spec:
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: keppel-anycast-nginx
  template:
    metadata:
      labels:
        name: keppel-anycast-nginx
      annotations:
        checksum/configmap: {{ include "keppel/templates/configmap-anycast.yaml" . | sha256sum }}
        kubectl.kubernetes.io/default-container: nginx
    spec:
      containers:
      - name: nginx
        image: {{ $.Values.global.dockerHubMirrorAlternateRegion }}/library/nginx:{{$.Values.keppel.anycast_nginx_tag}}
        imagePullPolicy: IfNotPresent
        env:
          - name: "NGINX_ENTRYPOINT_LOCAL_RESOLVERS"
            value: "true"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/templates/proxy.conf.template
          subPath: proxy.conf.template
        - name: tls-cert
          mountPath: /etc/nginx/ssl
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
      volumes:
      - name: nginx-config
        configMap:
          name: keppel-anycast-nginx
      - name: tls-cert
        secret:
          secretName: tls-keppel-api-san
{{- end }}
