apiVersion: v1
kind: ServiceAccount
metadata:
  name: keppel-generate-issuer-key

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keppel-generate-issuer-key

rules:
  # The "keppel-generate-issuer-key" CronJob writes into this secret.
  - apiGroups: [ "" ]
    resources: [ secrets ]
    verbs:     [ get, patch, update ]
    resourceNames: [ keppel-issuer-key ]

  # "create" permission cannot be restricted to specific resourceNames
  # Ref: <https://stackoverflow.com/a/65203104>
  - apiGroups: [ "" ]
    resources: [ secrets ]
    verbs:     [ create ]

  # need the UID of the cronjob to render an owner reference
  - apiGroups: [ batch ]
    resources: [ cronjobs ]
    verbs:     [ get ]
    resourceNames: [ keppel-generate-issuer-key ]

  # There is a post-install hook next to the CronJob that needs to be able to trigger it once.
  - apiGroups: [ batch ]
    resources: [ jobs ]
    verbs:     [ create ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keppel-generate-issuer-key
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keppel-generate-issuer-key
subjects:
  - kind: ServiceAccount
    name: keppel-generate-issuer-key
    namespace: {{ quote .Release.Namespace }}
