{{- if .Values.keppel.anycast_domain_name }}
apiVersion: disco.stable.sap.cc/v1
kind: Record
metadata:
  name: keppel-global.{{ .Values.global.region }}{{ .Values.global.tld }}
spec:
  type: A
  record: 10.46.101.103
  hosts:
    - keppel-global.{{ .Values.global.region }}{{ .Values.global.tld }}
{{ end }}
