{{- range $key, $cluster := .Values.persephoneShoots }}
{{- $defaultAuthConfigName := printf "authentication-seed-%s" $key | trunc 63 | trimSuffix "-" }}
{{- if $cluster.oidcConfig.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $defaultAuthConfigName }}
  namespace: garden
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  config.yaml: |
    apiVersion: apiserver.config.k8s.io/v1beta1
    kind: AuthenticationConfiguration
{{- with $cluster.oidcConfig.anonymous }}
    anonymous:
{{ toYaml . | indent 6 }}
{{- end }}
    jwt:
{{ toYaml $cluster.oidcConfig.jwt | indent 6 }}
{{- end }}
{{- end }}
