{{- range $key, $cluster := .Values.persephoneShoots }}
{{- $infraCredsName := default "openstack-infra-creds-seed" $cluster.infraCredentialsSecretName }}
---
apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: ManagedSeed
metadata:
  name: {{ $key }}{{ $cluster.landscapeName | substr 0 1 }}
  namespace: garden
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shoot:
    name: {{ $key }}{{ $cluster.landscapeName | substr 0 1 }}
  gardenlet:
    config:
      apiVersion: gardenlet.config.gardener.cloud/v1alpha1
      kind: GardenletConfiguration
      gardenClientConnection:
        gardenClusterAddress: https://api.virtual.{{ $cluster.landscapeName }}.persephone.{{ $cluster.region }}.cloud.sap
      logging:
        enabled: true
      seedConfig:
        metadata:
          labels:
            environment: {{ $cluster.landscapeName }}
        spec:
{{- if $cluster.backup }}
          backup:
{{ toYaml $cluster.backup | indent 12 }}
{{- end }}
          dns:
            defaults:
            - credentialsRef:
                apiVersion: v1
                kind: Secret
                name: {{ $infraCredsName }}
                namespace: garden
              type: openstack-designate
              domain: external.{{ $cluster.landscapeName }}.persephone.{{ $cluster.region }}.cloud.sap
            internal:
              credentialsRef:
                apiVersion: v1
                kind: Secret
                name: {{ $infraCredsName }}
                namespace: garden
              type: openstack-designate
              domain: internal.{{ $cluster.landscapeName }}.persephone.{{ $cluster.region }}.cloud.sap
            provider:
              credentialsRef:
                apiVersion: v1
                kind: Secret
                name: {{ $infraCredsName }}
                namespace: garden
              secretRef:
                name: {{ $infraCredsName }}
                namespace: garden
              type: openstack-designate
          settings:
            excessCapacityReservation:
              enabled: false
            dependencyWatchdog:
              prober:
                enabled: false
            loadBalancerServices:
              externalTrafficPolicy: Local
              zonalIngress:
                enabled: false
{{- if $cluster.loadBalancerServices }}
{{- if $cluster.loadBalancerServices.annotations }}
              annotations:
{{ toYaml $cluster.loadBalancerServices.annotations | indent 16 }}
{{- end }}
{{- end }}
{{- end }}