---
apiVersion: v1
kind: Secret
metadata:
  name: openstack-infra-creds-seed
  namespace: garden
type: Opaque
stringData:
  domainName: ccadmin
  tenantName: persephone-{{ required "missing value for .Values.landscapeName" .Values.landscapeName }}
  authURL: {{ required "missing value for .Values.keystone.authURL" .Values.keystone.authURL | quote }}
  applicationCredentialID: {{ required "missing required .Values.keystone.application_credential_id" .Values.keystone.application_credential_id | quote }}
  applicationCredentialSecret: {{ required "missing required value .Values.keystone.application_credential_secret" .Values.keystone.application_credential_secret | quote }}
---
apiVersion: security.gardener.cloud/v1alpha1
kind: CredentialsBinding
metadata:
  name: openstack-infra-creds-seed
  namespace: garden
provider:
  type: openstack
credentialsRef:
  apiVersion: v1
  kind: Secret
  name: openstack-infra-creds-seed
  namespace: garden