{{- range $key, $cluster := .Values.persephoneShoots }}
{{- $seedShootName := printf "%s%s" $key ($cluster.landscapeName | substr 0 1) }}
{{- $seedIngressDomain := printf "ingress.%s.garden.external.%s.persephone.%s.cloud.sap" $seedShootName $cluster.landscapeName $cluster.region }}
{{- if $cluster.wildcardCertificate }}
{{- if $cluster.wildcardCertificate.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-ingress-{{ $seedShootName }}
  namespace: garden
spec:
  commonName: "*.{{ $seedIngressDomain }}"
  dnsNames:
    - "*.{{ $seedIngressDomain }}"
    - "{{ $seedIngressDomain }}"
  issuerRef:
    group: certmanager.cloud.sap
    kind: ClusterIssuer
    name: digicert-issuer
  secretName: wildcard-ingress-{{ $seedShootName }}-tls
  secretTemplate:
    labels:
      gardener.cloud/role: controlplane-cert
  usages:
    - digital signature
    - key encipherment
{{- end }}
{{- end }}
{{- end }}
