schema:
  type: object
  properties:
    hint:
      type: string
    regexes:
      type: array
      items:
        type: string

testValues:
  hint: 'disabled due to CVE-2021-25742'
  regexes: [ "^ingress.kubernetes.io/(?:auth|configuration|server|modsecurity)-snippet$" ]
