{{ if and .Values.extensions.metal.enabled .Values.gardenlet.enabled -}}
---
apiVersion: security.gardener.cloud/v1alpha1
kind: WorkloadIdentity
metadata:
  name: metal-wi
  namespace: garden
spec:
  audiences:
    - metal-api
  targetSystem:
    type: ironcore-metal
{{- end }}
