{{- if .Values.extensions.seedIngressCertificates.enabled -}}
---
apiVersion: core.gardener.cloud/v1
kind: ControllerDeployment
metadata:
  name: seed-ingress-certificates
helm:
  ociRepository:
{{ toYaml .Values.extensions.seedIngressCertificates.helm.ociRepository | indent 4 }}
  values:
    certificate:
      secretName: {{ .Values.extensions.seedIngressCertificates.certificate.secretName }}
      issuerRef:
{{ toYaml .Values.extensions.seedIngressCertificates.certificate.issuerRef | indent 8 }}
      usages:
{{ toYaml .Values.extensions.seedIngressCertificates.certificate.usages | indent 8 }}
---
apiVersion: core.gardener.cloud/v1
kind: ControllerRegistration
metadata:
  name: seed-ingress-certificates
spec:
  deployment:
    deploymentRefs:
      - name: seed-ingress-certificates
    seedSelector: {}
{{- end }}
