apiVersion: v2
name: metal-onboarding-operator
description: Kubernetes operator for bare-metal server onboarding via DHCP and NetBox
type: application
version: 0.1.0
appVersion: "latest"
kubeVersion: ">= 1.29"
dependencies:
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: '>= 0.0.0'
