global:
  vcenter_operator_master_password: nase
  registry: mund
  keystoneNamespace: auge
imageVersion: ohr
username: kopf
password: arm
tsig_key: bein
role_id: fuss
secret_id: zeh
ad_ttu_username: hand
ad_ttu_password: finger
active_directory: hals
vault_url: knie
mount_point_read: rücken
mount_point_write: bauch
mount_point_write_nsxt: kinn
max_time_not_seen: 0
vault_check_interval: 1
password_digits: 2
password_length: 3
password_symbols: 4
