{{- if .Values.nannies }}
{{- $release_name := .Release.Name }}
{{- range $name, $settings := .Values.nannies }}
{{- if $settings.enabled }}
{{- $release := printf "%s-%s" $release_name $name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $release }}
data:
  nanny.yaml: |
{{ toYaml $settings.config | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
