apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config
  namespace: kube-system
data:
  webhooks.yaml: |
    # Source: metal-operator/templates/webhook/webhooks.yaml
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: metal-operator-validating-webhook-configuration
      namespace: kube-system
      annotations:
      labels:
        helm.sh/chart: "0.4.0-crds"
        app.kubernetes.io/name: metal-operator
        app.kubernetes.io/instance: metal-operator
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/managed-by: Helm
    webhooks:
      - name: vbiossettings-v1alpha1.kb.io
        clientConfig:
          url: https://metal-operator-webhook-service:443/validate-metal-ironcore-dev-v1alpha1-biossettings
        failurePolicy: Fail
        sideEffects: None
        admissionReviewVersions:
          - v1
        rules:
          - operations:
              - CREATE
              - UPDATE
              - DELETE
            apiGroups:
              - metal.ironcore.dev
            apiVersions:
              - v1alpha1
            resources:
              - biossettings
      - name: vbiosversion-v1alpha1.kb.io
        clientConfig:
          url: https://metal-operator-webhook-service:443/validate-metal-ironcore-dev-v1alpha1-biosversion
        failurePolicy: Fail
        sideEffects: None
        admissionReviewVersions:
          - v1
        rules:
          - operations:
              - CREATE
              - UPDATE
              - DELETE
            apiGroups:
              - metal.ironcore.dev
            apiVersions:
              - v1alpha1
            resources:
              - biosversions
      - name: vbmcsecret-v1alpha1.kb.io
        clientConfig:
          url: https://metal-operator-webhook-service:443/validate-metal-ironcore-dev-v1alpha1-bmcsecret
        failurePolicy: Fail
        sideEffects: None
        admissionReviewVersions:
          - v1
        rules:
          - operations:
              - CREATE
              - UPDATE
              - DELETE
            apiGroups:
              - metal.ironcore.dev
            apiVersions:
              - v1alpha1
            resources:
              - bmcsecrets
      - name: vbmcsettings-v1alpha1.kb.io
        clientConfig:
          url: https://metal-operator-webhook-service:443/validate-metal-ironcore-dev-v1alpha1-bmcsettings
        failurePolicy: Fail
        sideEffects: None
        admissionReviewVersions:
          - v1
        rules:
          - operations:
              - CREATE
              - UPDATE
              - DELETE
            apiGroups:
              - metal.ironcore.dev
            apiVersions:
              - v1alpha1
            resources:
              - bmcsettings
      - name: vbmcversion-v1alpha1.kb.io
        clientConfig:
          url: https://metal-operator-webhook-service:443/validate-metal-ironcore-dev-v1alpha1-bmcversion
        failurePolicy: Fail
        sideEffects: None
        admissionReviewVersions:
          - v1
        rules:
          - operations:
              - CREATE
              - UPDATE
              - DELETE
            apiGroups:
              - metal.ironcore.dev
            apiVersions:
              - v1alpha1
            resources:
              - bmcversions
      - name: vendpoint-v1alpha1.kb.io
        clientConfig:
          url: https://metal-operator-webhook-service:443/validate-metal-ironcore-dev-v1alpha1-endpoint
        failurePolicy: Fail
        sideEffects: None
        admissionReviewVersions:
          - v1
        rules:
          - operations:
              - CREATE
              - UPDATE
            apiGroups:
              - metal.ironcore.dev
            apiVersions:
              - v1alpha1
            resources:
              - endpoints
      - name: vserver-v1alpha1.kb.io
        clientConfig:
          url: https://metal-operator-webhook-service:443/validate-metal-ironcore-dev-v1alpha1-server
        failurePolicy: Fail
        sideEffects: None
        admissionReviewVersions:
          - v1
        rules:
          - operations:
              - DELETE
            apiGroups:
              - metal.ironcore.dev
            apiVersions:
              - v1alpha1
            resources:
              - servers
    # Source: metal-operator/templates/prometheus/monitor.yaml
    # To integrate with Prometheus.
