apiVersion: v2
name: kvm-ha-service
description: Helm Chart for KVM HA Service with internal dependencies
type: application

version: 0.1.3

dependencies:
- name: kvm-ha-service
  version: '1.0.4'
  repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
- name: owner-info
  repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
  version: '>= 0.0.0'
- name: utils
  repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
  version: 0.22.1
- name: linkerd-support
  repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
  version: ~1
