apiVersion: v2
name: consumer-fixture
description: Smoke-test consumer of the neutron-linuxbridge-agent library chart.
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: neutron-linuxbridge-agent
    version: 0.1.0
    repository: file://../..
  - name: utils
    version: '>= 0.0.0'
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
