global:
  registry: registry.example.com

imageVersion: caracal

linuxbridge_agent:
  secretName: linuxbridge-agent-secret

  # Mode B: library generates the ConfigMap.
  configMap:
    name: ""
    key: neutron.conf
  host: ""
  agent:
    polling_interval: 2
  vxlan:
    enable: true
  securitygroup:
    firewall_driver: iptables
