defaultUpdateStrategy: AutoRollingUpdate
greenhouseShootGrafter: greenhouse-prod-sci
purpose: production
authenticationConfig: {}
kvmShoot: false
auditing:
  configMapName: audit-policy-cp-compute
  secretName: auditing-mtls-compute
networking:
  enableBirdExporter: true
  overlay: true
  externalServiceAssignmentMode: Automatic
workerDefaults:
  channel: release
  feature: stable
  machineControllerManager:
    machineCreationTimeout: 1h20m0s
    machineHealthTimeout: 1h0m0s
    machineDrainTimeout: 240h0m0s
    inPlaceUpdateTimeout: 1h20m0s
coredump:
  enabled: false
