{
 "title": "DocumentationHealth",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Documentation PODS [QA-DE-1]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{namespace=\"documentation\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "SSL HEALTH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Documentation Website [HOME] SSL Health ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "probe_http_ssl{instance=\"https://documentation.global.cloud.sap\", job=\"docs-urls\"}"
    }
   ]
  },
  { "title": "Loading Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Documentation Website [HOME]  Duration in Seconds ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 10 },
   "format": "s",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(sum_over_time(probe_http_duration_seconds{instance=\"https://documentation.global.cloud.sap/api/public/project/documentation.global.cloud.sap?version=NULL\", job=\"docs-home-content\"}[5m]))"
    }
   ]
  },
  { "title": "WEBSITE HEALTH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Documentation Website [HOME] Health ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://documentation.global.cloud.sap\", job=\"docs-urls\"}"
    }
   ]
  },
  {
   "title": "Documentation Website [BLOG] Health ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://documentation.global.cloud.sap/blog\", job=\"docs-urls\"}"
    }
   ]
  },
  {
   "title": "Documentation Website [TRAINING] Health ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "probe_success{instance=\"https://documentation.global.cloud.sap/training\", job=\"docs-urls\"}"
    }
   ]
  },
  { "title": "CONTENT CHECK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Documentation Website [TRAINING] Content",
   "type": "singlestat",
   "description": "Expected Content:\n\n- \"Welcome to the SAP Converged Cloud classroom Training\"\n- \"Here you will find our three day course agenda and material\"\n- \"The objective of the classroom training is to be as hands-on an experience as possible\"",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "probe_success{job=\"docs-training-content\"}"
    }
   ]
  },
  {
   "title": "Documentation Website [HOME] Content ",
   "type": "singlestat",
   "description": "Expected Content:\n- \"SAP Converged Cloud\"\n- \"From Playground to Production on one Infrastructure-as-a-Service\"\n- \"powered by Kubernetes\"\n- \"Getting Started\"\n- \"Monsoon Automation\"\n- \"Global distribution\"\n- \"Email Service\"",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "probe_success{job=\"docs-home-content\"}"
    }
   ]
  }
 ]
}