{{- if .Values.encryptionRotation.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-encryption-rotation
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: encryption-rotation
{{- end }}
