{{- if .Values.encryptionRotation.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etcd-encryption-rotation
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: encryption-rotation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etcd-encryption-rotation
subjects:
  - kind: ServiceAccount
    name: etcd-encryption-rotation
    namespace: {{ .Release.Namespace }}
{{- end }}
