apiVersion: v1
kind: ConfigMap
metadata:
  name: cc-gardener-backup
  namespace: {{ .Release.Namespace }}
data:
  backup-garden-cluster.sh: |
{{ include (print .Template.BasePath "/etc/_backup.tpl") . | indent 4 }}
