apiVersion: v1
kind: Secret
metadata:
  name: cc-gardener-backup
  namespace: {{ .Release.Namespace }}
data:
  backup-os-application-credential-id: {{ required ".Values.backup.applicationCredentialId is required" .Values.backup.applicationCredentialId | b64enc }}
  backup-os-application-credential-secret: {{ required ".Values.backup.applicationCredentialSecret is required" .Values.backup.applicationCredentialSecret | b64enc }}
