apiVersion: v1
kind: Secret
metadata:
  name: cc-gardener-backup
  namespace: {{ .Release.Namespace }}
data:
  vault-role-id: {{ required ".Values.vault.roleId is required" .Values.vault.roleId | b64enc }}
  vault-secret-id: {{ required ".Values.vault.secretId is required" .Values.vault.secretId | b64enc }}
