---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cc-gardener-backup
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cc-gardener-backup
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cc-gardener-backup
subjects:
- kind: ServiceAccount
  name: cc-gardener-backup
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cc-gardener-backup
  apiGroup: rbac.authorization.k8s.io
