persephoneShoots:
  pseed-1:
    region: "eu-de-1"
    landscapeName: "landscape"
    seedName: "the seed"
    purpose: testing
    floatingPoolName: FloatingNetwork
    keystone:
      authURL: "https://x.y.z"
      application_credential_id: "abc"
      application_credential_name: "abc"
      application_credential_secret: "secret"

    oidcConfig:
      enabled: false
      jwt: []

    highAvailability:
      enabled: true
      
    kubernetes:
      version: 1.2.3
      verticalPodAutoscaler:
        enabled: true
    
    workers: []