{{- if .Values.global.barbican_external_ip }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-external
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    system: openstack
    type: api
    component: barbican
  annotations:
    projectcalico.org/loadBalancerIPs: '["{{ .Values.global.barbican_external_ip }}"]'
    {{- include "utils.linkerd.pod_and_service_annotation" . | indent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
    - {{ .Values.global.barbican_external_ip }}
  selector:
    name: barbican-api
  ports:
    - name: public
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: disco.stable.sap.cc/v1
kind: Record
metadata:
  name: {{ include "barbican_api_endpoint_host_public" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: A
  record: {{ .Values.global.barbican_external_ip }}
  hosts:
    - {{ include "barbican_api_endpoint_host_public" . }}
  zoneName: {{ .Values.global.region }}.{{ .Values.global.tld }}
{{- end }}
