apiVersion: v1
kind: Secret
metadata:
  name: elektra-secrets
data:
  monsoon.openstack.auth.api.password: {{ .Values.monsoon_openstack_auth_api_password | b64enc}}
  two-factor-radius-secret: {{ .Values.two_factor_radius_secret | b64enc }} 

---
{{- if eq .Values.global.region "eu-de-3" }}
apiVersion: v1
kind: Secret
metadata:
  name: ingress-ca-cert
data:
  ca.crt:
    {{ .Values.ingress.tls_client_auth.cacrt | b64enc | quote }}
{{- end }}

