{{- if .Values.tests.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GkLibtestValidation
metadata:
  name: libtest-validation
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["ConfigMap"]
    scope: Namespaced
{{- end }}
