ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_add_node_trait_duplicate_trait : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_add_node_trait_long : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_add_node_trait_non_existent_node : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_add_node_trait_too_long : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_add_node_trait_too_many : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_list_node_traits : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_list_node_traits_non_existent_node : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_list_nodes_detail : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_list_nodes_traits_field : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_remove_node_trait : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_remove_node_trait_non_existent_node : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_remove_node_trait_non_existent_trait : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_remove_node_traits : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_remove_node_traits_no_traits : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_remove_node_traits_non_existent_node : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_set_node_traits : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_set_node_traits_duplicate_trait : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_set_node_traits_max_traits : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_set_node_traits_non_existent_node : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_set_node_traits_too_many : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_show_node : Traits are not available until Queens release
ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesTraits.test_update_node_traits : Traits are not available until Queens release
