owner-info:
  support-group: observability
  maintainers:
  - Tommy Sauer
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/openstack/observability-seeds

# defaults applied to each entry in `projects` when the entry does not
# override the field itself.
defaults:
  description: SCI observability infrastructure related components. Check project name for scope.
  cidr: 10.180.0.0/16
  routerExternalSubnet: FloatingIP-external-monsoon3-01-03@monsoon3-shared-infra@monsoon3

# projects is a list of OpenStack projects to seed. One OpenstackSeed
# resource is emitted per entry.
projects:
- name: sci-observability-metrics
  # required
  technicalUser:
  # optional
  cidr:
  description: 
