apiVersion: v2
description: Chart to deploy agent sandbox.
name: agent-sandbox
version: 0.0.1
dependencies:
# Owner info adds a configmap to the kubernetes cluster with information on
# the service owner. This makes it easier to find out who to contact in case
# of issues. See: https://github.com/sapcc/helm-charts/pkgs/container/helm-charts%2Fowner-info
- name: owner-info
  repository: oci://ghcr.io/sapcc/helm-charts
  version: 1.0.0
