# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: persephone-liquid-apiserver
description: Persephone Liquid API Server for managing Gardener shoot cluster quotas via Limes
type: application
version: 1.0.7
appVersion: "1.0.0"
keywords:
  - persephone
  - limes
  - liquid
  - gardener
  - quota
maintainers:
  - name: Caio Ronchi
  - name: Sandro Jaeckel
  - name: Jan Knipper
dependencies:
- name: owner-info
  repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
  version: '>= 0.0.0'
