{{- if eq .Values.mode "shoot" }}
apiVersion: v1
kind: Namespace
metadata:
  name: metal-servers
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- include "chart.additionsAnnotations" . | nindent 4 }}
{{- end }}
