{{- if eq .Values.mode "seed" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: remote-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- include "chart.additionsAnnotations" . | nindent 4 }}
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/remote-serviceaccount/ca.crt
        server: https://{{ required "controllerManager.manager.env.KUBERNETES_SERVICE_HOST is required" .Values.controllerManager.manager.env.KUBERNETES_SERVICE_HOST }}
      name: remote
    contexts:
    - context:
        cluster: remote
        user: sa
      name: remote
    current-context: remote
    users:
    - name: sa
      user:
        tokenFile: /var/run/secrets/kubernetes.io/remote-serviceaccount/token
{{- end }}
