{{- if eq .Values.mode "seed" }}
apiVersion: v1
kind: Secret
metadata:
  name: metal-operator-remote-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    resources.gardener.cloud/purpose: token-requestor
    resources.gardener.cloud/class: shoot
  annotations:
    {{- include "chart.additionsAnnotations" . | nindent 4 }}
    serviceaccount.resources.gardener.cloud/name: metal-operator-controller-manager
    serviceaccount.resources.gardener.cloud/namespace: kube-system
    serviceaccount.resources.gardener.cloud/inject-ca-bundle: "true"
type: Opaque
stringData:
  token: ""
  bundle.crt: ""
{{- end }}
