apiVersion: v2
name: metal-maintenance-operator
description: A Helm chart for the Ironcore metal-maintenance-operator.
type: application
version: 0.1.1
dependencies:
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: '>= 0.0.0'
  - name: metal-maintenance-operator
    repository: oci://ghcr.io/ironcore-dev/charts
    version: 0.0.1-20260625130151-4aa3159
    alias: metal-maintenance-operator-core
