{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keystone-saml-sp-cert-monitor
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  github-token: {{ .Values.githubToken | b64enc | quote }}
{{- end }}
