apiVersion: v2
name: etcd-kcp-ops
description: A Helm chart for etcd KCP backup and encryption key rotation
type: application
version: 0.2.0
dependencies:
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: '>= 0.0.0'
