global:
  # The DNS domain to be used for all Greenhouse components.
  dnsDomain:
  # OIDC configuration for Greenhouse.
  oidc:
    issuer:
    redirectURL:
    clientID:
    clientSecret:
  supportGroup: "containers"
  caCert: my-cert

# disable secrets-injector per default
secrets-injector:
  enabled: false

# Organization & IDProxy should be enabled only after the initial install of greenhouse
organization:
  enabled: true
  oauth2ClientRedirectURIs:
    - "http://localhost:33768"
    - "http://localhost:33768/auth/callback"
    - "http://localhost:8000"
    - "http://localhost:18000"
    - https://repo.eu-de-1.cloud.sap/via-oidc/index.html

catalogs:
  observability-tagged:
    labels:
      greenhouse.sap/owned-by: observability
    sources:
      - repository: https://github.com/cloudoperators/greenhouse-extensions
        ref:
          branch: main # using main for QA and playground, can be changed to a specific tag or commit for production
        resources:
          - alerts/plugindefinition.yaml
          - audit-logs/plugindefinition.yaml
          - kube-monitoring/plugindefinition.yaml
          - logs/plugindefinition.yaml
          - logshipper/plugindefinition.yaml
          - opensearch/plugindefinition.yaml
          - perses/plugindefinition.yaml
          - prometheus/plugindefinition.yaml
          - supernova/plugindefinition.yaml
          - thanos/plugindefinition.yaml
        overrides:
          - name: alerts
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/greenhouse-extensions/charts
          - name: audit-logs
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/greenhouse-extensions/charts
          - name: kube-monitoring
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/greenhouse-extensions/charts
          - name: logs
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/greenhouse-extensions/charts
          - name: logshipper
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/greenhouse-extensions/charts
          - name: opensearch
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/greenhouse-extensions/charts
          - name: perses
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/greenhouse-extensions/charts
          - name: prometheus
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/greenhouse-extensions/charts
          - name: thanos
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/greenhouse-extensions/charts

  containers-tagged:
    labels:
      greenhouse.sap/owned-by: containers
    sources:
      - repository: https://github.com/cloudoperators/greenhouse-extensions
        ref:
          branch: main # using main for QA and playground, can be changed to a specific tag or commit for production
        resources:
          - doop/plugindefinition.yaml
          - exposed-services/plugindefinition.yaml
          - kubeconfig-generator/plugindefinition.yaml
          - service-proxy/plugindefinition.yaml
          - repo-guard/plugindefinition.yaml
          - cert-manager/plugindefinition.yaml
          - digicert-issuer/plugindefinition.yaml
          - disco/plugindefinition.yaml
          - ingress-nginx/plugindefinition.yaml
          - reloader/plugindefinition.yaml
          - shoot-grafter/plugindefinition.yaml
        overrides:
          - name: exposed-services
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/greenhouse-extensions/charts
          - name: kubeconfig-generator
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/greenhouse-extensions/charts
          - name: repo-guard
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/charts
          - name: service-proxy
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/greenhouse-extensions/charts
          - name: cert-manager
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/greenhouse-extensions/charts
          - name: digicert-issuer
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/sapcc/helm-charts
          - name: disco
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
          - name: ingress-nginx
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-registry-k8s-io-mirror/ingress-nginx/charts
          - name: reloader
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/stakater/charts
          - name: shoot-grafter
            repository: oci://keppel.eu-de-1.cloud.sap/ccloud-ghcr-io-mirror/cloudoperators/greenhouse-extensions/charts
      - repository: https://github.wdf.sap.corp/sap-cloud-infrastructure/greenhouse-extensions
        ref:
          branch: main # using main for QA and playground, can be changed to a specific tag or commit for production
        resources:
          - secrets-injector/plugindefinition.yaml
          - ldap-named-user/plugindefinition.yaml
        secretName: github-app-secret-sci
        overrides:
          - name: secrets-injector
          - name: ldap-named-user

scim:
  enabled: false
  # authType: basic | token
  # username:
  # password:
  # bearerToken:
  # bearerHeader:
  # bearerPrefix:

# Configures core Greenhouse teams.
teams:
  # An admin team must be specified. Additional teams are optional.
  # admin:
  #   description:
  #   mappedIdPGroup:
  #   supportRBAC: true

### Configure several Plugins for the Greenhouse organization below.

certManager:
  webhook:
    timeoutSeconds: 15
# Configures the DigiCert issuer for the Greenhouse organization,
# which enables obtaining DigiCert certificates via the cert-manager.
digicertIssuer:
  enabled: false
  apiToken:
  organizationID:
  organizationUnits:
  caCertID:

# Configures the DISCO, Designate Ingress CNAME operator, for the Greenhouse organization,
# which enables automated management of DNS records with OpenStack Designate.
disco:
  enabled: false
  record:
  zoneName:
  authURL:
  regionName:
  username:
  userDomainName:
  password:
  projectName:
  projectDomainName:

# Configures the NGINX ingress for the Greenhouse organization, which enables external access.
ingress:
  enabled: true
  # Specify the loadBalancer IP for the ingress service.
  # loadBalancerIP:
  # redirect ccloud org
  redirectCCloudOrg: false

monitoring:
  enabled: false
  supportGroup: observability
  alertmanager:
    enabled: false

thanos:
  enabled: false
  supportGroup: observability

alerts:
  enabled: false
  supportGroup: observability
  # Supernova options.
  endpoint:

  slack:
    channel:
    webhookURL:

  ingress:
    host:

  filterLabels:
    - app
    - service
    - severity
    - organization
  silenceExcludedLabels:
    - pod
    - pod_name
    - instance
  silenceTemplates: []

  predefinedFilters: []

  # Alertmanager options.
  alertmanager:
    # Whether to deploy the alertmanager.
    enabled: false

logshipping:
  enabled: false
  supportGroup: observability
  fluent-bit:
    image:
      repository: cr.fluentbit.io/fluent/fluent-bit
    hotReload:
      image:
        repository: ghcr.io/jimmidyson/configmap-reload

openTelemetry:
  enabled: false
  supportGroup: observability
  # set via secrets
  #   region:
  #   cluster:
  #   openSearchLogs
  #     username:
  #     password:
  #     endpoint:
  logsCollector:
    enabled: true
  metricsCollector:
    enabled: true
  prometheus:
    podMonitor:
      enabled: true
    serviceMonitor:
      enabled: true
  admissionWebhooks:
    certManager:
      enabled: true
    autoGenerateCert:
      enabled: false
      recreate: false
  kubeRBACProxy:
    enabled: false
  manager:
    prometheusRule:
      defaultRules:
        enabled: false
      enabled: false
perses:
  enabled: true
  supportGroup: observability

shootgrafter:
  enabled: true
  supportGroup: containers

repoguard:
  enabled: false
