{{- if (index .Values (print .Chart.Name | replace "-" "_")).tempest.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: tempest
    type: config
type: Opaque
stringData:
  tempest-admin-password: {{ .Values.tempestAdminPassword | quote }}
{{- end }}
