apiVersion: v2
description: Per-node daemon that seeds the kernel entropy pool using the CPU jitter RNG
name: jitterentropy-rngd
version: 0.1.0
appVersion: "1.2.9"
maintainers:
  - name: bbobrov
  - name: rajivmucheli
  - name: databus23
dependencies:
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: 1.0.0
