{{- if .Values.netappsd.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netapp-monitoring.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  netappUsername: {{ .Values.netappsd.netappUsername  }}
  netappPassword: {{ .Values.netappsd.netappPassword }}
  netboxToken: {{ .Values.netappsd.netboxToken }}
  netboxHost: {{ .Values.netappsd.netboxHost }}
{{- end }}