{{- if .Values.netappsd.enabled }}
{{- range $appName, $appValues := .Values.apps }}
{{- if $appValues.enabled }}
{{- with $ }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netapp-monitoring.fullname" . }}-{{ $appName }}-master
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-monitoring.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ include "netapp-monitoring.fullname" . }}-{{ $appName }}-master
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: netappsd
        prometheus.io/scrape: "true"
        prometheus.io/targets: storage
      labels:
        app: {{ include "netapp-monitoring.fullname" . }}-{{ $appName }}
        name: {{ include "netapp-monitoring.fullname" . }}-{{ $appName }}-master
    spec:
      serviceAccountName: {{ .Values.netappsd.serviceAccountName | default "netappsd" }}
      containers:
        - name: netappsd
          image: "{{ .Values.netappsd.image.repository }}:{{ .Values.netappsd.image.tag }}"
          imagePullPolicy: {{ .Values.netappsd.image.pullPolicy | default "IfNotPresent" }}
          command: ["/netappsd", "master"]
          args:
            - --region
            - {{ .Values.netappsd.region }}
            - --tag
            - {{ $appName }}
            - --listen-addr
            - 0.0.0.0:{{ .Values.netappsd.ports.master }}
            - --worker
            - {{ include "netapp-monitoring.fullname" . }}-{{ $appName }}-worker
          env:
            - name: NETAPP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "netapp-monitoring.fullname" . }}-sd
                  key: netappUsername
            - name: NETAPP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "netapp-monitoring.fullname" . }}-sd
                  key: netappPassword
            - name: NETBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "netapp-monitoring.fullname" . }}-sd
                  key: netboxToken
            - name: NETBOX_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "netapp-monitoring.fullname" . }}-sd
                  key: netboxHost
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: metrics
              containerPort: {{ .Values.netappsd.ports.master }}
          resources:
            {{- toYaml .Values.netappsd.resources | nindent 12 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}