{{- if .Values.netappsd.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netapp-monitoring.fullname" . }}-sd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  netappUsername: {{ .Values.netappsd.netapp_exporter_user | b64enc | quote }}
  netappPassword: {{ .Values.netappsd.netapp_exporter_password | b64enc | quote }}
  netboxToken: {{ .Values.netappsd.netbox_api_token | b64enc | quote }}
  netboxHost: {{ .Values.netappsd.netbox_host | b64enc | quote }}
{{- end }}