{{- if .Values.netappsd.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netapp-monitoring.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netapp-monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  netappUsername: Q0NvcHNST3VzZXI=
  netappPassword: dnU0aHVFZ1NwcEdYdk1UbmJ0R3o1cjBvYjBDSmJT
  netboxToken: NmJiMzk0YmYzMmVhMGMwODFmYTNiNThiNDkwZWVmODhlZDU5MmQyNg==
  netboxHost: aHR0cHM6Ly9uZXRib3guZ2xvYmFsLmNsb3VkLnNhcA==
{{- end }}