apiVersion: v2
name: metal-maintenance-operator-remote
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: owner-info
    repository: oci://keppel.eu-de-1.cloud.sap/ccloud-helm
    version: '>= 0.0.0'
  - name: metal-maintenance-operator
    repository: oci://ghcr.io/ironcore-dev/charts
    version: 0.0.1-20260721080039-86549d3-crds
    alias: metal-maintenance-operator-core
