apiVersion: v1
kind: ConfigMap
metadata:
  name: remote-kubeconfig
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/remote-serviceaccount/ca.crt
        server: https://{{ .Values.controllerManager.manager.env.KUBERNETES_SERVICE_HOST }}
      name: remote
    contexts:
    - context:
        cluster: remote
        user: sa
      name: remote
    current-context: remote
    users:
    - name: sa
      user:
        tokenFile: /var/run/secrets/kubernetes.io/remote-serviceaccount/token