apiVersion: v1
kind: ServiceAccount
metadata:
  name: metal-operator-webhook-injector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metal-operator-webhook-injector
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metal-operator-webhook-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metal-operator-webhook-injector
subjects:
  - kind: ServiceAccount
    name: metal-operator-webhook-injector
