apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-saml-sp-cert-exporter-config
  namespace: {{ .Values.exporter.namespace }}
data:
  config.yaml: |
    region: {{ required ".Values.exporter.region missing" .Values.exporter.region }}
