apiVersion: v1
kind: Secret
metadata:
  name: keystone-saml-sp-cert-exporter-github
  namespace: {{ .Values.exporter.namespace }}
type: Opaque
data:
  token: {{ required ".Values.exporter.githubToken missing" .Values.exporter.githubToken | b64enc }}
