{{- if not (has .Release.Namespace (list "garden" "garden-compute" "garden-storage")) -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    gardener.cloud/role: project
    project.gardener.cloud/name: {{ include "cc-shoots-workerless.clusterType" . }}
---
apiVersion: core.gardener.cloud/v1beta1
kind: Project
metadata:
  name: {{ include "cc-shoots-workerless.clusterType" . }}
spec:
  namespace: {{ .Release.Namespace }}
{{- end }}
