apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-console-nginx
  labels:
    system: openstack
    type: configuration
    component: ironic

data:
  nginx.conf: |
{{ include (print .Template.BasePath "/etc/_nginx.conf.tpl") . | indent 4 }}
