owner-info:
  support-group: containers
  service: billing
  maintainers:
    - Stefan Majewsky
    - Sandro Jäckel
  helm-chart-url: https://github.com/sapcc/helm-charts/tree/master/openstack/billing
