apiVersion: v1
kind: Service
metadata:
  name: metal-operator-webhook-service
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/name: metal-operator
    control-plane: controller-manager
